feat: display personalized category and product data
intershop/intershop-pwa pull request #1021
Opened 2022-02-18 17:36 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
Category and product REST calls are sent without pgid (unpersonalized). Category views, personalized product prices or promotions defined in the ICM back office are not respected in the storefront.

Issue Number: Closes #315

## What Is the New Behavior?
Category and product data are personalized.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2022-02-22 14:40 UTC, dhhyi commented on src/app/core/utils/meta-reducers.ts
> +export function resetPersonalizedShoppingMeta(reducer: ActionReducer<ShoppingState>): ActionReducer<ShoppingState> {
This is very specific to the shopping store, so maybe it should be declared there.

Alternatively, you could generalize it a bit, something like `resetSubStatesOnLogoutMeta<T>(subStates: keyOf T): ((reducer: ActionReducer<T>) => ActionReducer<T>)`, that uses `lodash-es` `omit` on the state.

2022-03-07 09:09 UTC, Eisie96 requested changes

2022-03-07 10:08 UTC, shauke commented on src/app/core/store/customer/user/user.actions.ts
> +export const waitForSPGIDComplete = createAction('[User Internal] Wait for SPGID Complete');
* rename `setPGID` to `loadPGID`
* rename `setPGIDSuccess` to `loadPGIDSuccess`
* map error to `loginUserFail`
* rename `waitForSPGIDComplete` to `personalizationStatusDetermined`

2022-03-07 21:30 UTC, shauke approved these changes

2022-03-07 21:33 UTC, merged