feat: display maintenance page in case of a 503 http status error
intershop/intershop-pwa pull request #1111
Opened 2022-04-08 12:22 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
If the ICM server is in maintenance mode REST requests respond with an 503 http status code, but the client doesn`t handle these errors properly.

Issue Number: Closes #

## What Is the New Behavior?
The pwa shows a maintenance page if a REST request respond with a 503 error.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2022-09-01 08:07 UTC, shauke requested changes

2022-09-01 14:43 UTC, jometzner commented
@shauke @SGrueber We can now retest the integration with ICM again, as the WA is now capable of handling CORS preflight requests in the maintenance case.

2022-09-06 09:02 UTC, shauke requested changes

2022-09-06 09:09 UTC, shauke commented on src/assets/i18n/fr_FR.json
> +  "server.maintenance.page.text": "Nous sommes désolés ...</h3><h4></h4>",
@mglatter & @NicolasGrizard The other localizations should be reviewed as well. Thank you.

2022-09-09 09:46 UTC, jometzner commented on src/app/shell/header/header-error/header-error.component.html
> +        href="/home"
This is not working in a prod like deployment with multi-channel basehref configuration

2022-09-12 13:41 UTC, jometzner approved these changes

2022-09-22 06:33 UTC, shauke submitted a review, later dismissed

2022-09-22 07:44 UTC, NicolasGrizard requested changes
see both comments

2022-09-22 07:44 UTC, NicolasGrizard commented on src/assets/i18n/fr_FR.json
> +  "server.maintenance.page.contact.label": "You can contact us:",
should maybe be in french: "Vous pouvez nou contacter:",

2022-09-22 07:44 UTC, NicolasGrizard commented on src/assets/i18n/fr_FR.json
> +  "server.maintenance.page.title": "Arrêts de maintenance",
it should be "arrêt", no plural s

2022-09-22 15:33 UTC, shauke approved these changes

2022-09-23 06:47 UTC, merged