fix: only update cost center when it actually changes
intershop/intershop-pwa pull request #1153
Opened 2022-05-05 12:11 UTC by MaxKless

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently, when you navigate to the basket page and the user has only one cost center, the cost center is nevertheless reassigned and because of this, the basket is reloaded. This leads to certain error/information messages to dissapear.

## What Is the New Behavior?
Now, the cost center is only reassigned when it actually differs from the one already set in the basket.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2022-05-06 06:07 UTC, SGrueber requested changes

2022-05-06 06:07 UTC, SGrueber commented on src/app/shared/components/basket/basket-cost-center-selection/basket-cost-center-selection.component.ts
> +        if (costCenter !== basket.costCenter) {
This condition has to be a bit more precise - "", undefined and null values have to be treated as the same, if a user has more than one cost center 2 requests are send if the user enters cart page setting the cost center null and "" , but actually no request should be sent in this case, see image

2022-05-06 06:08 UTC, SGrueber commented
![image](https://user-images.githubusercontent.com/57660644/167076380-f746f067-e6ad-482c-a2d9-8902f351e143.png)

2022-05-06 06:09 UTC, SGrueber commented
![image](https://user-images.githubusercontent.com/57660644/167076474-79f1b644-2eb2-496d-bb76-91601bcd641d.png)

2022-05-10 16:39 UTC, M-Behr approved these changes

2022-05-16 11:29 UTC, SGrueber approved these changes

2022-05-16 12:01 UTC, merged