feat/customer reviews
intershop/intershop-pwa pull request #1158
Opened 2022-05-10 22:14 UTC by paramaeder

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently there is no feature to display customer reviews

Issue Number: Closes 76116

## What Is the New Behavior?

If there is at least one product review then there is a reviews tab shown in the product-detail-info.component which can show customer reviews

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

2022-05-17 09:09 UTC, SGrueber commented
The ui looks fine, just 2 hints: The heading for the review display should be 'Recent Product Reviews' . If there are no reviews to display the message 'There are no reviews submitted yet' should be shown. Please, check also the provided IAD. https://www.figma.com/file/6Ccec915dDuc2DIMf89ALj/Product-Reviews?node-id=1%3A448

2022-05-17 12:41 UTC, SGrueber requested changes

2022-05-17 12:41 UTC, SGrueber commented on src/app/core/services/reviews/reviews.service.ts
> +      tap(customer => {
Does the review REST api really require this? If not, remove the customer selection stuff

2022-05-17 12:41 UTC, SGrueber commented on src/app/core/models/product-reviews/product-reviews.mapper.ts
> +  static fromData(productReviewsData: ProductReviewData[], sku: string): ProductReviews {
I'd prefer the order sku, productReviews

2022-05-17 12:41 UTC, SGrueber commented on src/app/core/services/reviews/reviews.service.ts
> +    params.append('sku', sku);
is this necessary? the sku ist part of the url?

2022-05-17 12:41 UTC, SGrueber commented on src/app/core/store/shopping/products/products.effects.ts
> +  loadProductReviewsAfterProductSuccess$ = createEffect(() =>
loading of the product review should be triggered by the product-reviews. component with the help of a facade method

2022-05-17 12:41 UTC, SGrueber commented on src/app/core/store/shopping/product-reviews/product-reviews.actions.ts
> +export const loadProductReviews = createAction('[Product Review] Load Product Reviews', payload<{ skus: string[] }>());
we don't need to fetch the reviews of more than one product so we the parameter should be sku of type string

2022-05-19 12:34 UTC, SGrueber requested changes

2022-05-19 12:34 UTC, SGrueber commented on src/app/shared/components/product/product-reviews/product-reviews.component.html
> +    <div class="row pb-3">
add class 'review-item' here

2022-05-19 12:34 UTC, SGrueber commented on src/app/shared/components/product/product-reviews/product-reviews.component.html
> +          <span *ngIf="lastStar" class="mb-0 h5 font-weight-light"> {{ review.title }}</span>
use class 'review-item-header-title' here - define further styles in the ratings.scss if needed

2022-05-19 12:34 UTC, SGrueber commented on src/app/shared/components/product/product-reviews/product-reviews.component.spec.ts
> +  });
maybe add another test here to check that a review is displayed

2022-05-19 13:23 UTC, SGrueber requested changes

2022-05-19 13:23 UTC, SGrueber commented on src/app/core/facades/shopping.facade.ts
> +    this.store.dispatch(loadProductReviews({ sku }));
I suggest to check here if the feature is enabled - so an action LoadProductReviews is never called if the feature is off:
 getProductReviews$(sku: string) {
    if (this.featureToggleService.enabled('rating')) {
      this.store.dispatch(loadProductReviews({ sku }));
    }
    return this.store.pipe(select(getProductReviewsBySku(sku)));
  }

2022-05-19 20:53 UTC, paramaeder commented on src/app/shared/components/product/product-reviews/product-reviews.component.html
> +        {{ review.creationDate | date: 'MMM d, y, h:mm:ss a' }}
Is it possible that the pipe can only display the date, but not the time?

2022-05-20 06:46 UTC, SGrueber commented on src/app/shared/components/product/product-reviews/product-reviews.component.html
> +        {{ review.creationDate | date: 'MMM d, y, h:mm:ss a' }}
You can use all format options of the angular date pipe: https://angular.io/api/common/DatePipe
This should be the one you need:  {{ review.creationDate | ishDate: 'medium' }}

2022-05-23 14:20 UTC, SGrueber requested changes

2022-05-23 14:20 UTC, SGrueber commented on src/app/core/services/reviews/reviews.service.ts
> +    return this.currentCustomer$.pipe(
this is still not necessary: return this.apiService... should be enough

2022-05-23 14:20 UTC, SGrueber commented on src/app/core/store/shopping/product-reviews/product-reviews.reducer.ts
> +  on(loadProductReviews, state => ({ ...state, loading: true })),
pls use the methods setLoadingOn, unsetLoadingAndErrorOn, 

make sure, loading is set by the load action, and unset by the fail and success action and the error is reseted at least by the next success action

2022-05-25 09:33 UTC, SGrueber commented on src/app/core/store/shopping/product-reviews/product-reviews.effects.spec.ts
> +    it('should map invalid request to action of type loadProductReviewsFail', () => {
Usually we also test the the mapping to the success action

2022-05-25 09:35 UTC, SGrueber commented on src/app/shared/components/product/product-reviews/product-reviews.component.ts
> +    this.error$ = this.context.productReviewsError$;
use the method of the shopping facade shopping facade here

2022-05-25 11:37 UTC, dhhyi requested changes
This feature should be externalized into an extension. I doubt every shop will use it.

2022-05-25 13:20 UTC, mglatter commented on src/assets/i18n/fr_FR.json
> +  "product.reviews.heading": "Notations",
_Reviews_ and _submit_ are translated differently according to our translation memory system. Please ask Nicolas for review of fr_FR.json

2022-05-25 13:21 UTC, mglatter reviewed
Approved for DE and EN JSON files, for FR please ask Nicolas for a review.

2022-05-31 09:24 UTC, SGrueber commented
the changes are part of the pr #1174

2022-05-31 09:24 UTC, closed without merging