Refactor/rating extension
intershop/intershop-pwa pull request #1174
Opened 2022-05-31 09:20 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
On product detail page product reviews are not display.
The number behind the rating stars of a product displays the average rating (bug).

Issue Number: Closes #

## What Is the New Behavior?
On product detail page the user can click a reviews tab to see the review comments of other users. Creating a review comment is still pending and will be done soon.
The number behind the rating stars displays the number of ratings.
The rating feature is implemented in an extension.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2022-05-31 12:09 UTC, NicolasGrizard requested changes

2022-05-31 12:09 UTC, NicolasGrizard commented on src/assets/i18n/fr_FR.json
> +  "product.reviews.heading": "Notations",
*Avis

2022-05-31 12:09 UTC, NicolasGrizard commented on src/assets/i18n/fr_FR.json
> +  "product.reviews.no_reviews_yet.text": "Aucune critique n'a encore été soumise.",
*Aucun avis n'a encore été soumis.

2022-05-31 12:37 UTC, dhhyi requested changes

2022-05-31 12:37 UTC, dhhyi commented on src/app/core/facades/product-context.facade.ts
> +  reviews: ProductReview[];
Should not be part of this facade

2022-05-31 12:37 UTC, dhhyi commented on src/app/core/models/product-reviews/product-review.model.ts
> +export interface ProductReview {
Should be moved to the extension

2022-05-31 17:23 UTC, SGrueber commented
There is still an issue left: If the user opens the reviews tab the reviews are fetched from the server twice. This has to be solved before the PR can be merged.

2022-06-02 10:35 UTC, dhhyi requested changes

2022-06-02 10:35 UTC, dhhyi commented on src/app/extensions/rating/shared/product-rating-star/product-rating-star.component.ts
> +@GenerateLazyComponent()
Not needed, right? 🤔

2022-06-02 10:35 UTC, dhhyi commented on src/app/extensions/rating/rating.module.ts
> +  exports: [ProductRatingComponent, ProductRatingStarComponent, ProductReviewsComponent, SharedModule],
`ProductRatingStarComponent` doesn't need export, I think

2022-06-02 17:01 UTC, shauke submitted a review, later dismissed

2022-06-02 17:02 UTC, shauke commented
> There is still an issue left: If the user opens the reviews tab the reviews are fetched from the server twice. This has to be solved before the PR can be merged.

Issue was fixed by removing doubled `productReviews$ | async ` pipe.

2022-06-03 04:55 UTC, dhhyi approved these changes
:+1:

2022-06-03 05:57 UTC, merged