feat: design preview support
intershop/intershop-pwa pull request #1216
Opened 2022-07-18 17:04 UTC by shauke

## PR Type

[x] Feature

## What Is the New Behavior?

Initial Design Preview support (!!! NOT Design View with editing capabilities !!!)

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

2022-07-26 14:53 UTC, jometzner commented
`PreviewInterceptor` is not SSR compatible. Session Storage reference doesn't work

2022-11-16 15:07 UTC, Eisie96 requested changes

2022-12-09 09:12 UTC, shauke commented
Requires ICM 7.10.39.1 once it is GA.

2023-01-16 17:56 UTC, marschmidt89 approved these changes
documentation changes approved

2023-01-16 20:11 UTC, merged