fix: show success messages for cost center buyer actions (#959)
intershop/intershop-pwa pull request #1249
Opened 2022-08-17 11:36 UTC by DiverDori

## PR Type

[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
There are no success messages for actions with cost center users. https://github.com/intershop/intershop-pwa/issues/959

Issue Number: Closes #959

## What Is the New Behavior?
There are new success messages for cost center users, in particular for adding, removing and updating the buyer. 

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x ] No

## Other Information

2022-08-18 10:45 UTC, SGrueber commented
Maybe the content of the messages should be more precise:
Suggestion:
"Add Buyer": The user "Jack Link" has been added to the cost center.
"Edit Budget": The budget of user "Jack Link" has been updated.
"Remove Buyer": The user "Jack Link" has been removed from the cost center.

2022-08-18 11:12 UTC, SGrueber requested changes

2022-08-18 11:12 UTC, SGrueber commented on projects/organization-management/src/app/store/cost-centers/cost-centers.effects.ts
> +              messageParams: { 0: `${payload.buyer.login}` },
`${payload.buyer.firstName} ${payload.buyer.lastName}` || `${payload.buyer.login}`

to make it work the firstName and lastName has to be added to the CostCenterBuyer object in the method submitCostCenterBuyerForm()  of the cost-center-buyer-edit-dialog.component

2022-08-18 14:05 UTC, schadii approved these changes
Tnx, It is Okay.

2022-08-22 10:10 UTC, SGrueber submitted a review, later dismissed

2022-08-31 12:58 UTC, merged