feat: CMS navigation components (link, page, category)
intershop/intershop-pwa pull request #1266
Opened 2022-09-08 14:49 UTC by shauke

## PR Type

[x] Feature

## What Is the New Behavior?

Introduce new CMS components that can be used to extend the main navigation.
* simple link with optional flyout HTML
* page link with optional sub pages navigation and flyout HTML
* category link with optional sub pages navigation and flyout HTML

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

* some main navigation styling adaptions were needed
* the needed pagelet models will be available with ICM 7.10.38.??-LTS

2024-02-28 12:28 UTC, SGrueber requested changes

2024-02-28 12:28 UTC, SGrueber commented on src/app/shared/cms/components/cms-navigation-category/cms-navigation-category.component.spec.ts
> +  it('should be created', () => {
tests are missing

2024-02-28 12:28 UTC, SGrueber commented on src/app/shared/cms/components/cms-navigation-link/cms-navigation-link.component.spec.ts
> +  it('should be created', () => {
tests

2024-02-28 12:28 UTC, SGrueber commented on src/app/shared/cms/components/cms-navigation-link/cms-navigation-link.component.ts
> +  @Input() pagelet: ContentPageletView;
required?

2024-02-28 12:28 UTC, SGrueber commented on src/app/shared/cms/components/cms-navigation-page/cms-navigation-page.component.spec.ts
> +  it('should be created', () => {
tests

2024-02-28 12:28 UTC, SGrueber commented on src/app/shared/cms/components/cms-navigation-page/cms-navigation-page.component.ts
> +  @Input() pagelet: ContentPageletView;
required

2024-02-29 10:17 UTC, shauke commented on src/app/shared/cms/components/cms-freestyle/cms-freestyle.component.html
> +  [ngClass]="pagelet.stringParam('CSSClass')"
This change is reverted since the Freestyle HTML component does not have the CSSClass configuration parameter. I don't know where I saw this?

2024-02-29 10:51 UTC, shauke commented on src/app/core/store/shopping/categories/categories.selectors.ts
> +function mapNavigationCategoryFromId(
This I can do. ;)

2024-03-07 10:42 UTC, shauke commented on src/app/core/store/shopping/categories/categories.effects.ts
> +          mapErrorToAction(loadCategoryTreeFail)
removed

2024-03-08 17:23 UTC, SGrueber submitted a review, later dismissed

2024-03-11 08:05 UTC, andreassteinmann approved these changes

2024-03-11 10:00 UTC, merged