feature: message to merchant component first design
intershop/intershop-pwa pull request #1323
Opened 2022-11-10 16:10 UTC by DilaraGueler

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2023-01-12 12:06 UTC, SGrueber requested changes
pls, add an e2e test

2023-01-12 13:54 UTC, SGrueber requested changes

2023-01-12 13:54 UTC, SGrueber commented on src/app/shared/components/basket/basket-merchant-message/basket-merchant-message.component.ts
> +@Component({
please add a short component documentation

2023-01-12 13:59 UTC, SGrueber requested changes

2023-01-12 13:59 UTC, SGrueber commented on src/environments/environment.b2b.ts
> +    'messageToMerchant',
pls. mention the new feature toggle in the migrations.md

2023-01-30 17:03 UTC, marschmidt89 approved these changes
no complaints regarding the .md file from my side

2023-01-31 12:06 UTC, iwiederhold requested changes
![merchant_message_edit_missing](https://user-images.githubusercontent.com/38127411/215755121-eb0662f7-5047-4a79-998e-18a7f443b6e4.gif)

--------------------------------------------------------------------------------------------------------

![merchant_message_label_spaces](https://user-images.githubusercontent.com/38127411/215755124-4b0dbb22-5de7-416a-a496-4762bf8da3ed.gif)

2023-02-02 08:59 UTC, schadii approved these changes
Thanks!

2023-02-02 09:14 UTC, SGrueber approved these changes

2023-02-08 13:13 UTC, schadii submitted a review, later dismissed

2023-02-08 13:38 UTC, iwiederhold commented
After editing the merchant message again, you get an error.

![image](https://user-images.githubusercontent.com/38127411/217545725-37078884-2909-42ab-933d-cc8efa532d69.png)

2023-02-08 14:45 UTC, DilaraGueler commented
>

2023-02-09 09:57 UTC, SGrueber approved these changes

2023-02-09 09:59 UTC, merged