feat: my Account menu navigation grouping
intershop/intershop-pwa pull request #1331
Opened 2022-11-24 08:06 UTC by tdonthu

BREAKING CHANGES:
My Account menu will display group wise

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
Menu navigation in My Account page currently displaying individually 

Issue Number: Closes #

## What Is the New Behavior?
Menu navigation in My Account page will display group wise for B2B
## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2023-02-06 08:52 UTC, SGrueber commented
It would be good if the first menu item is always expanded after the user logged in. This might help the user to see that there are more options in the menu than he can see at first glance.
If the menu is collapsed lines are missing between the navigation items.

2023-02-06 09:13 UTC, shauke commented
@iwiederhold @schadii Please review the changed Account Navigation if it meets your ideas. Please consider and answer the issues Silke addressed in her review. Styling was already discussed, so the missing lines are currently intended, but could be changed if necessary. Especially the partitioning should probably be discussed. Thank you.

2023-02-06 09:21 UTC, iwiederhold submitted a review, later dismissed

2023-02-06 09:28 UTC, schadii submitted a review, later dismissed

2023-02-06 10:14 UTC, SGrueber commented
The logout link has been moved from the top to the button. If the organization menu is open it looks like an organization item ?

![image](https://user-images.githubusercontent.com/57660644/216945227-9006d9f3-cb40-4cee-b824-844e9db1a77d.png)

2023-02-06 10:31 UTC, SGrueber commented
Why is payment under MyOrganization. Aren't payment instruments, like credit cards etc. specific to the user?

2023-02-06 11:55 UTC, SGrueber commented
The My Organization menu item is empty for a punchout user and should not be visible.


![image](https://user-images.githubusercontent.com/57660644/216965042-fcb72030-2175-4c45-b26f-4f3abfc07009.png)

2023-02-06 11:57 UTC, SGrueber requested changes

2023-02-06 11:57 UTC, SGrueber commented on src/app/pages/account/account-navigation/account-navigation.items.b2c.ts
> +  {
even if you switch on b2b features in the environment.properties they won't work in b2c - so imo it is not necessary to leave them in this file: requisitions, approvals, costcenters, user management

2023-02-08 11:44 UTC, SGrueber approved these changes

2023-02-08 13:04 UTC, schadii submitted a review, later dismissed
Thanks.

2023-02-08 13:33 UTC, iwiederhold submitted a review, later dismissed
👍

2023-02-23 07:35 UTC, shauke approved these changes

2023-02-23 07:49 UTC, merged