feat: keyboard accessibility rule added
intershop/intershop-pwa pull request #1336
Opened 2022-12-07 14:35 UTC by DilaraGueler

## PR Type

[ ] Bugfix
[X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Accessibility with keyboard is missing for some components.

Issue Number: Closes #

Accessibility rule is added to the eslint rules and required components adjusted to the new rule. It is possible to use the website with a keyboard instead of a mouse. 

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ X] No

## Other Information

2022-12-09 07:43 UTC, SGrueber requested changes
Pls, revert all unnecessary changes and note a few further remarks below.

2022-12-09 07:43 UTC, SGrueber commented on .eslintrc.json
> +        "@angular-eslint/template/click-events-have-key-events": "warn"
pls, use error here - to support key events is mandatory from now on

2023-01-06 16:39 UTC, marschmidt89 submitted a review, later dismissed
Documentation reviewed and approved

2023-01-11 10:57 UTC, shauke submitted a review, later dismissed

2023-01-11 12:59 UTC, shauke approved these changes

2023-01-11 17:13 UTC, shauke approved these changes

2023-01-11 17:14 UTC, merged