feat: provide and combine metrics of theme instances
intershop/intershop-pwa pull request #1340
Opened 2022-12-12 18:55 UTC by jometzner

## PR Type

[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
When switching `PROMETHEUS=on` one metrics endpoint for SSR is exposed. That endpoint merely provides insights into PM2 "orchestrator" but [default metrics](https://github.com/siimon/prom-client#default-metrics) of Node.js processes are missing.

## What Is the New Behavior?
Provide above mentioned default metrics of Node.js + the possibility to include custom metrics on aggregated metrics registries.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ x ] No

## Other Information

2022-12-12 19:56 UTC, jometzner commented on src/ssr/server-scripts/prometheus.js
> +                  data: {
`data` characteristic can be removed as the receiver doesn't need

2022-12-13 10:39 UTC, Eisie96 requested changes

2022-12-13 10:39 UTC, Eisie96 commented on src/ssr/server-scripts/prometheus.js
> +    if (msg?.data?.topic == 'returnMetrics' && msg.process.name && msg.process.pm_id) {
Use === instead of == as equality operator

2022-12-14 09:59 UTC, Eisie96 approved these changes

2022-12-14 14:18 UTC, merged