fix: scrollbar added to the approval tabs
intershop/intershop-pwa pull request #1353
Opened 2023-01-10 16:01 UTC by DilaraGueler

## PR Type

[ X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

On the phone view, the tabs have long names in the approval section. The complete page gets a horizontal scrollbar.

Issue Number: Closes #988

## What Is the New Behavior?

The horizontal scrollbar is only usable for the tabs. The rest of the content is fixed. 

## Does this PR Introduce a Breaking Change?

[ ] Yes
[X ] No

## Other Information

2023-01-20 08:43 UTC, SGrueber requested changes
ui improvements needed for firefox (hide scrollbar, suppress unwanted lines)

2023-02-02 09:42 UTC, SGrueber requested changes

2023-02-02 09:42 UTC, SGrueber commented on src/styles/global/global.scss
>  .nav-tabs::-webkit-scrollbar {
move this style statement into the nav-tabs block ( e.g. to line 141 ) using the & operator:
  &::-webkit-scrollbar {.....

2023-02-02 15:18 UTC, iwiederhold requested changes
Please test the scrolling behavior on your phone too. On my phone the tabs move up and down when scrolling.

2023-02-09 10:00 UTC, SGrueber approved these changes

2023-02-09 10:02 UTC, SGrueber commented
> Please test the scrolling behavior on your phone too. On my phone the tabs move up and down when scrolling.

We won't fix this, it is a minor issue only occurring on iphones.

2023-02-09 10:03 UTC, merged