feat: product warranties
intershop/intershop-pwa pull request #1368
Opened 2023-02-07 10:56 UTC by shauke

## PR Type

[x] Feature

## What Is the Current Behavior?

The PWA does not yet handle product warranties.

Issue Number: Closes  #1062

## What Is the New Behavior?

Product warranties are displayed at the product detail page, in the basket and in the checkout process.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2024-01-04 15:59 UTC, iwiederhold commented
![alignement_warranties](https://github.com/intershop/intershop-pwa/assets/38127411/6a36dd7a-7173-4a23-b660-eff19d756368)

2024-01-04 16:08 UTC, iwiederhold commented
![Uploading remove_border.jpg…]()

2024-01-04 16:22 UTC, iwiederhold commented
![remove_border](https://github.com/intershop/intershop-pwa/assets/38127411/a18571c9-b830-4f66-a46e-4d1f07654492)

2024-01-04 16:30 UTC, iwiederhold requested changes
See comments.

2024-01-05 13:23 UTC, schadii commented
In the detail modal, the phrase “Insurance against breakdown is repeated. Warranty period: 1 year.” twice. It may be clearer to mention it only once and then list the specific details under it. 

Please consider using bullet points or a numbered list for better readability, especially since you are detailing specific information. This can make it easier for the user to absorb the information.

The term "Expires: Service Plan" might be a bit confusing. Could not consider specifying the exact expiration date of the warranty or provide details on how the user can find this information?
<img width="1384" alt="Detail modal" src="https://github.com/intershop/intershop-pwa/assets/105789331/e954770c-1709-466d-b97e-085d84b61a65">

2024-01-08 12:13 UTC, schadii approved these changes

2024-01-08 12:23 UTC, iwiederhold approved these changes

2024-01-15 07:24 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "product.warranty.heading.text": "Protect your purchase:",
Sounds like it was insecure to buy anything in our online shop. Would suggest rephrasing it to "Protect your purchased product" or some other headline that makes clear that this is about a warranty for products.

2024-01-15 07:28 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "product.warranty.no_protection_plan": "No protection plan",
What is meant by protecttion plan? Is it the same as the service plan mentioned in the modal Shadi commented on?

2024-01-15 07:33 UTC, mglatter commented on src/assets/i18n/de_DE.json
> +  "product.warranty.no_protection_plan": "Kein Schutzplan",
"Schutzplan" sounds quite dramatic. Is this the correct term to use in context of product warranties? Browsing the net, I'm not so sure about it.

2024-01-15 13:41 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "product.warranty.heading.text": "Protect your purchase:",
Suggestion: "Product warranty options:",

2024-01-15 13:41 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "product.warranty.no_protection_plan": "No protection plan",
Suggestion: "No warranty",

2024-01-15 14:03 UTC, mglatter commented
I will change the English wording to the suggestions agreed on with Shadi and will provide updated localization values for the other languages as well.

2024-01-17 14:53 UTC, mglatter approved these changes

2024-04-25 10:44 UTC, merged