chore:adjusted french and german translations
intershop/intershop-pwa pull request #1470
Opened 2023-08-03 11:23 UTC by AMenzelInterShop

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[x] Other: adjusted french & german translations

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

2023-08-03 11:31 UTC, marschmidt89 requested changes

2023-08-03 11:31 UTC, marschmidt89 commented on src/assets/i18n/de_DE.json
>    "application.recentlyViewed.heading": "Ihre Browsing-Historie",
```suggestion
  "application.recentlyViewed.heading": "Ihre Browserverlauf",
```

2023-08-03 11:31 UTC, marschmidt89 commented on src/assets/i18n/fr_FR.json
>    "account.wishlists.wishlist_form.name.error.required": "Veuillez entrer un nom pour la liste de souhaits.",
```suggestion
  "account.wishlists.wishlist_form.name.error.required": "Veuillez saisir un nom pour la liste de souhaits.",
```

2023-08-03 11:36 UTC, marschmidt89 commented on src/assets/i18n/de_DE.json
> +  "product.label.topseller.text": "Beliebt",
```suggestion
  "product.label.topseller.text": "TOP",
```

Please leave it as it is.

2023-08-07 07:52 UTC, shauke approved these changes

2023-08-07 07:55 UTC, merged