refactor: required parameters
intershop/intershop-pwa pull request #1498
Opened 2023-08-31 13:46 UTC by LucasHengelhaupt

## PR Type

[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Documentation content changes

## What Is the Current Behavior?
All component input parameters are optional. 

## What Is the New Behavior?

Mandatory component input parameters are declared as required to ensure that all necessary data is provided, catching potential errors early.

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

[AB#92105](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/92105)

2023-09-04 09:46 UTC, SGrueber requested changes

2023-09-07 08:41 UTC, LucasHengelhaupt commented on src/app/pages/account-payment/account-payment/account-payment.component.ts
>    @Input() paymentMethods: PaymentMethod[];
made required

2023-09-07 08:56 UTC, LucasHengelhaupt commented on src/app/shell/header/sub-category-navigation/sub-category-navigation.component.ts
> +  @Input({ required: true }) categoryUniqueId: string;
changed order

2023-09-07 08:57 UTC, LucasHengelhaupt commented on src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.ts
> +  @Input({ required: true }) control: AbstractControl;
changed order

2023-09-07 08:57 UTC, LucasHengelhaupt commented on src/app/pages/account-profile-email/account-profile-email/account-profile-email.component.ts
> +  @Input({ required: true }) currentUser: User;
changed order

2023-09-07 08:58 UTC, LucasHengelhaupt commented on src/app/pages/account-profile-company/account-profile-company/account-profile-company.component.ts
> +  @Input({ required: true }) currentCustomer: Customer;
changed order

2023-10-12 09:47 UTC, SGrueber approved these changes

2023-12-13 12:23 UTC, SGrueber approved these changes

2023-12-13 12:26 UTC, merged