refactor: renamed 'id' to 'productListingId'
intershop/intershop-pwa pull request #1504
Opened 2023-09-07 12:34 UTC by LucasHengelhaupt

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2023-09-08 11:34 UTC, SGrueber requested changes

2023-09-08 11:34 UTC, SGrueber commented on src/app/shared/components/product/product-listing/product-listing.component.ts
> +    if (changes.id && this.productListingId?.value) {
here you forgot something :-)

2023-09-11 08:36 UTC, LucasHengelhaupt commented on src/app/shared/components/product/product-listing/product-listing.component.ts
> +    if (changes.id && this.productListingId?.value) {
fixed it :)

2023-09-13 11:14 UTC, SGrueber approved these changes

2023-09-13 11:15 UTC, merged