feat: wishlist sharing
intershop/intershop-pwa pull request #1590
Opened 2024-02-29 12:26 UTC by fgiesske-intershop

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

The wishlist sharing feature of the old "Responsive Starter Store" is missing in the PWA

## What Is the New Behavior?

The wishlist sharing (B2C only) functionality from the old Starter Store is now also added to the PWA

- share wish lists with other users with a link
- automatically opens the user email client with a pre-prepared message and the link to the shared wishlist
- display the shared wishlist

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information
requires ICM-AS 11.9.0

2024-03-05 13:47 UTC, SGrueber requested changes
- replace the feature toggle by a server configuration attribute or remove it
- move your code to the wishlist extension if possible

2024-04-05 15:20 UTC, SGrueber requested changes

2024-04-05 15:20 UTC, SGrueber commented on src/app/extensions/wishlists/shared/wishlist-sharing-dialog/wishlist-sharing-dialog.component.spec.ts
> +  it('should be created', () => {
add tests to check the rendering of the component and the submit event

2024-09-30 10:30 UTC, M-Behr requested changes
- please check mobil view
![image](https://github.com/user-attachments/assets/ba99a74a-4482-4368-a6f8-b69dded46a67)
- Are the floating buttons accessible? Tooltip needed? Maybe icon buttons are better.
- E-mail client with a pre-prepared message is not visible after click on send:
![image](https://github.com/user-attachments/assets/d345774f-c5ed-4a36-8ba1-71fa54548206)
- Shared wish lists could be labeled in the wish list overview. Example:
![image](https://github.com/user-attachments/assets/97ce3bb5-a412-4e86-8344-7ee9569077a5)
- Displaying of shared wish list could not be reviewed because of not working e-mail. I need the URL in the E-mail to check if only this person have access to this shared wish list.

2024-10-04 09:06 UTC, SGrueber requested changes
Pls let's discuss ui fixes before you start to work on it

2024-10-14 14:54 UTC, mglatter commented
Ami will review French, so please do not merge beforehand.

2024-10-15 09:25 UTC, mglatter submitted a review, later dismissed
Localization has been approved (including French checked by Ami). Please let us know if you make any later changes to the wording. Then we will have another look.

2024-10-16 13:39 UTC, mglatter commented on src/assets/i18n/de_DE.json
>    "account.wishlists.table.preferred": "Standardliste",
See line 556: Wenn Sie eine Wunschliste zu Ihrer bevorzugten Wunschliste machen, werden alle anderen Listen (sofern vorhanden) auf Standard zurückgesetzt.

So, the translation "Standardliste" seems to be wrong here. Should be "Bevorzugt". French translation is fine. I'll adjust it for DE as well now.

2024-10-16 13:43 UTC, mglatter submitted a review, later dismissed

2024-10-22 15:20 UTC, iwiederhold commented
The status should not be appended to the name.
![image](https://github.com/user-attachments/assets/89c5f9bb-40bb-4c36-944a-dd4c3535ae80)

2024-10-23 12:37 UTC, M-Behr commented
Thanks for the fixes.
- The button group should be in one line with the heading.
![wishlist_buttongroup](https://github.com/user-attachments/assets/0da1d9ba-b3ec-438f-874e-38b9d3126a10)
- Please check the link in the e-mail. The b2c is not mentioned there, so it links to the B2B theme.
- If the wishlist is no longer shared, the "friend" can already open the link and see the list because it's cached.

2024-10-24 12:15 UTC, iwiederhold submitted a review, later dismissed

2024-10-24 12:16 UTC, M-Behr requested changes
Design issues are fixed. Well done!

@SGrueber follwing problem still exists:
I share my wish list to a friend. The friend can open it via link. I unshare my wish list. My friend can open it again with the link. If the friend uses another browser, the error page appears (this is correct). It looks like a caching problem. Could you check this, please?

2025-01-08 10:42 UTC, SGrueber approved these changes

2025-01-08 10:54 UTC, M-Behr approved these changes

2025-01-08 10:59 UTC, merged