feat: implementation of fast checkout payment (e.g. PAYPAL Expess) (#95945)
intershop/intershop-pwa pull request #1682
Opened 2024-06-12 10:07 UTC by skoch-intershop

## PR Type

[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Not possible to apply fast checkout payment methods.

Issue Number: Closes #95945 (ADO)

## What Is the New Behavior?

The fast checkout payment functionality is now applicable on the basket detail page. All available fast checkout payment methods will displayed in the summary slot .
![image](https://github.com/intershop/intershop-pwa/assets/62150160/46ad40e5-07e2-4c11-b615-5c45c18aa379)

## Does this PR Introduce a Breaking Change?
[ ] Yes
[n ] No

2024-06-13 16:06 UTC, SGrueber requested changes

2024-06-13 16:06 UTC, SGrueber commented on src/app/pages/basket/shopping-basket-payment/shopping-basket-payment.component.ts
> +  paymentCostThresholdReached(paymentMethod: PaymentMethod): boolean {
don't copy code - if you need the same functionality here as in the checkout-payment.component create a subcomponent or find another way to share the code

2024-07-19 16:09 UTC, SGrueber requested changes
it looks all much better than before 👍

2024-07-19 16:09 UTC, SGrueber commented on src/app/core/models/payment-method/payment-method.mapper.ts
> +    const invalidCapabilities = ['LimitedTender'];
getEligiblePaymentMethods now returns also fast checkout methods, pls write a migration note, that the selector has changed

2024-07-19 16:09 UTC, SGrueber commented on src/app/core/store/customer/basket/basket.actions.ts
> +export const setFastCheckoutPayment = createAction(
rename to setBasketFastCheckoutPayment

2024-07-19 16:09 UTC, SGrueber commented on src/app/core/store/customer/basket/basket-payment.effects.ts
> +  executeFastCheckoutRedirect$ = createEffect(
test ? see order.effects.spec

2024-08-06 08:29 UTC, iwiederhold reviewed
Please remove the space of 16px after the button-group. (B2B+B2C)

![image](https://github.com/user-attachments/assets/44e78ca5-7ba6-4139-a159-c47854c131bf)

For a better usability we should insert a space of 1rem between the checkout button and the other ones.

![image](https://github.com/user-attachments/assets/39eca9c3-7d20-4899-b096-5ae543bc2e5b)

2024-08-06 10:49 UTC, M-Behr requested changes
<img width="1064" alt="Paypal_express_error_payment_canceled" src="https://github.com/user-attachments/assets/2ed4330b-fe6c-4fa9-b9c3-e4399212abfe">

Please use a toast error message instead of this inline error message. Please create a new text for this error because the user does not see the payment methods here.

Error message for the cart page: "We're sorry. Your payment was canceled. You can continue with the checkout or use the express checkout."

2024-08-07 07:54 UTC, M-Behr commented
> Please remove the space of 16px after the button-group. (B2B+B2C)
> 
> ![image](https://private-user-images.githubusercontent.com/38127411/355369043-44e78ca5-7ba6-4139-a159-c47854c131bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTcxMTMsIm5iZiI6MTcyMzAxNjgxMywicGF0aCI6Ii8zODEyNzQxMS8zNTUzNjkwNDMtNDRlNzhjYTUtN2JhNi00MTM5LWExNTktYzQ3ODU0YzEzMWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDdlY2Y2OGVmYzVmMjY1OTU4ZTUxZmIzNTkxNjE0NmQ4NGJhMWJjMDNmYzE5ODkwYTBhMzVmY2I1OTNlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8TdbIrJxnw9fQJ61HCs7uDY6uASjSupBJq2-0-Wea0)
> 
> For a better usability we should insert a space of 1rem between the checkout button and the other ones. There used to be an "or" there. That was even better.
> 
> ![image](https://private-user-images.githubusercontent.com/38127411/355373310-39eca9c3-7d20-4899-b096-5ae543bc2e5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTcxMTMsIm5iZiI6MTcyMzAxNjgxMywicGF0aCI6Ii8zODEyNzQxMS8zNTUzNzMzMTAtMzllY2E5YzMtN2QyMC00ODk5LWIwOTYtNWFlNTQzYmMyZTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Yjg4NTAyMmNkYzU0YjM0OGVkYzA3ZjM0NGVkNTBhOWIxMzFmYjExOGNjNTg1NTAwZWNmZGNhYTE5NWYzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIk6Dm0qFjMOz_wFpi8jvwNSZUQ1w8MoNPSVsAfnaww)

We decided to show the "or" between checkout and express checkout button, exactly as it is in the Responsive Starter Store.

2024-08-19 12:12 UTC, merged