feat: Support for CXML self service configuration
intershop/intershop-pwa pull request #1683
Opened 2024-06-13 11:54 UTC by suschneider

## PR Type

[x] Feature

## What Is the Current Behavior?

It is not possible to configure specific configurations for CXML Punchout users in the PWA.

## What Is the New Behavior?

User specific configurations for CXML Punchout are possible in the MyAccount area of the PWA.

## Does this PR Introduce a Breaking Change?

[x] No

## Other Information

[AB#95963](https://dev.azure.com/intershop-com/Products/_workitems/edit/95963)

2024-08-05 11:33 UTC, mglatter commented on src/assets/i18n/de_DE.json
> +  "account.punchout.configure.link": "Konfigurieren {{0}}",
```suggestion
  "account.punchout.configure.link": "{{0}} konfigurieren",
```

2024-08-05 11:36 UTC, mglatter commented on src/assets/i18n/de_DE.json
> +  "account.punchout.cxml.configuration.helptext": "Verwenden Sie die folgenden Einstellungen, um den Inhalt des cXML-Punchout-Dokuments festzulegen. Eingestellte Werte können zurückgesetzt werden, um
```suggestion
  "account.punchout.cxml.configuration.helptext": "Verwenden Sie die folgenden Einstellungen, um den Inhalt des cXML-Punchout-Dokuments festzulegen. Eingestellte Werte können auf den angegebenen Standardwert zurückgesetzt werden.",
```

2024-08-05 11:45 UTC, marschmidt89 approved these changes
feat: added suggestions

2024-08-05 11:47 UTC, mglatter commented on src/assets/i18n/en_US.json
>    "account.punchout.cxml.info.url.helptext": "Please use the following URL for the punchout configuration in your cXML procurement system. For the sender credentials use the username as identity and
Identity and SharedSecret are in quotation marks in the other languages. Not needed in EN?

2024-08-07 14:13 UTC, SGrueber requested changes

2024-08-09 17:31 UTC, SGrueber requested changes

2024-08-09 17:31 UTC, SGrueber commented on src/app/extensions/punchout/services/punchout/punchout.service.ts
> +            )}/users/${user}/configurations`,
add encodeResourceId for the userId

2024-08-09 17:31 UTC, SGrueber commented on src/app/extensions/punchout/services/punchout/punchout.service.ts
> +            )}/users/${user}/configurations`,
add encodeResourceId for the userId

2024-08-09 17:31 UTC, SGrueber commented on src/app/extensions/punchout/services/punchout/punchout.service.ts
> +            `customers/${encodeResourceID(customer.customerNo)}/punchouts/${encodeResourceID(
the encoding of the resourceType is not necessary even this function is used elsewhere

2024-08-20 11:31 UTC, mglatter approved these changes

2024-08-20 12:12 UTC, merged