SHOWCASE - Copilot PoC
intershop/intershop-pwa pull request #1698
Opened 2024-07-15 10:24 UTC by 714Lemons

This is a showcase of the Copilot PoC which uses Flowise to deliver an "intelligent assistant".

The Endpoint is configurable through the environment.model.ts file.

2025-02-18 16:13 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "copilot.disclaimer.message": "By using this chatbot, you agree to the <a target=\"_blank\" href=\"https://intershop.com/en/terms-of-use\">Terms & Conditions</a>.",
There doesn't seem to exist any German or French equivalent of that page, so we will need to refer to the English one  for all locales for the time being.

2025-02-18 16:15 UTC, mglatter submitted a review, later dismissed
Localization approved, documentation review still needs to be done.

Note: The Copilot part of the localization is not in sentence case as the remaining PWA localization, because the Copilot styling cannot be accessed, and thus, it should be written as it will be displayed.

2025-02-19 10:41 UTC, mglatter submitted a review, later dismissed

2025-02-20 08:02 UTC, 714Lemons commented on src/assets/i18n/en_US.json
> +  "copilot.disclaimer.message": "By using this chatbot, you agree to the <a target=\"_blank\" href=\"https://intershop.com/en/terms-of-use\">Terms & Conditions</a>.",
German: https://www.intershop.com/de/datenschutz
French: https://www.intershop.com/fr/protection-des-donnees

But the AI-paragraph seems to only be on the german and english site currently. (I cant speek french)

2025-02-20 08:19 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "copilot.disclaimer.message": "By using this chatbot, you agree to the <a target=\"_blank\" href=\"https://intershop.com/en/terms-of-use\">Terms & Conditions</a>.",
This was about T&C, not Privacy Policy.

2025-02-20 08:26 UTC, 714Lemons commented on src/assets/i18n/en_US.json
> +  "copilot.disclaimer.message": "By using this chatbot, you agree to the <a target=\"_blank\" href=\"https://intershop.com/en/terms-of-use\">Terms & Conditions</a>.",
Oh sry i think this should be linked to Privacy Policy, i dont see any copilot related information on the Terms & Conditions.

2025-02-20 15:00 UTC, SGrueber requested changes
After closing the chatbot window and opening it again the former messages are still there.
This might be a security issue (e.g. in an internet cafe etc.)
I have no idea if it would be possible to delete the messages if the user closes the widget?
Or we should ask an expert if this is necessary or not.

2025-02-20 15:00 UTC, SGrueber commented on src/app/extensions/copilot/shared/copilot/copilot.component.ts
> +      .pipe(takeUntilDestroyed(this.destroyRef))
add take(1) here? Or can there be a situation the initializeCopilot has to be triggered more than once?

2025-02-20 15:00 UTC, SGrueber commented on src/app/extensions/copilot/store/copilot-config/copilot-config.effects.ts
> +  loadCopilotConfiguration$ = createEffect(() =>
test is missing?

2025-02-20 15:00 UTC, SGrueber commented on src/app/extensions/copilot/store/copilot-config/copilot-config.effects.ts
> +          .pipe(map(config => setCopilotConfig({ config })))
somehow the setCopilotConfig action is triggered twice, adding distinctUntilChanged() operator should fix it

2025-02-20 15:00 UTC, SGrueber commented on src/app/extensions/copilot/store/copilot-config/copilot-config.selectors.ts
> +export const getCopilotConfig = createSelector(getCopilotState, state => state?.copilotConfig);
test(s) are missing?

2025-02-20 15:08 UTC, 714Lemons commented on src/app/extensions/copilot/store/copilot-config/copilot-config.selectors.ts
> +export const getCopilotConfig = createSelector(getCopilotState, state => state?.copilotConfig);
@SGrueber To delete the history upon closing the parameter "clearChatOnReload" in "chatWindow" needs to be true.

2025-02-20 15:09 UTC, 714Lemons commented
> After closing the chatbot window and opening it again the former messages are still there. This might be a security issue (e.g. in an internet cafe etc.) I have no idea if it would be possible to delete the messages if the user closes the widget? Or we should ask an expert if this is necessary or not.

@SGrueber To delete the history upon closing the parameter "clearChatOnReload" in "chatWindow" needs to be true.

2025-02-20 17:22 UTC, shauke commented on src/app/core/utils/script-loader/script-loader.service.ts
> +  load(url: string, type?: string): Observable<ScriptType> {
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type

> **Attribute is not set (default), an empty string, or a JavaScript MIME type**
> Indicates that the script is a "classic script", containing JavaScript code. Authors are encouraged to omit the attribute if the script refers to JavaScript code rather than specify a MIME type. JavaScript MIME types are [listed in the IANA media types specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types#textjavascript).

The missing documentation I will add.

2025-02-20 17:28 UTC, shauke commented on src/app/extensions/copilot/shared/copilot/copilot.component.ts
> +      .pipe(takeUntilDestroyed(this.destroyRef))
You are right, this should only be loaded once.

2025-02-20 17:31 UTC, shauke commented
> > After closing the chatbot window and opening it again the former messages are still there. This might be a security issue (e.g. in an internet cafe etc.) I have no idea if it would be possible to delete the messages if the user closes the widget? Or we should ask an expert if this is necessary or not.
> 
> @SGrueber To delete the history upon closing the parameter "clearChatOnReload" in "chatWindow" needs to be true.

@714Lemons Should we enable this in our demo integration or leave it as it is and it can be changed in customer projects if wanted?

2025-02-20 17:55 UTC, 714Lemons commented
> > > After closing the chatbot window and opening it again the former messages are still there. This might be a security issue (e.g. in an internet cafe etc.) I have no idea if it would be possible to delete the messages if the user closes the widget? Or we should ask an expert if this is necessary or not.
> 
> > 
> 
> > @SGrueber To delete the history upon closing the parameter "clearChatOnReload" in "chatWindow" needs to be true.
> 
> 
> 
> @714Lemons Should we enable this in our demo integration or leave it as it is and it can be changed in customer projects if wanted?

@shauke Leave it as it is.

2025-02-21 09:13 UTC, mglatter commented on src/assets/i18n/fr_FR.json
> +  "copilot.footer.company": "Politique de confidentialité",
Does this key refer to the footer in the PWA? (In line 897, the line of the Intershop corporate website is used, where this is called "notes sur la protection des données". Does this have to match?

2025-02-21 09:16 UTC, mglatter commented on src/assets/i18n/en_US.json
> +  "copilot.disclaimer.message": "By using this chatbot, you agree to the <a target=\"_blank\" href=\"https://intershop.com/en/terms-of-use\">Terms & Conditions</a>.",
Adjusted links to lead to privacy policy

2025-02-21 10:27 UTC, iwiederhold commented
Please check the font family of the Intershop Copilot for our PWA. The PWA uses Roboto, but the copilot uses Open Sans.

2025-02-21 10:33 UTC, M-Behr commented
> > > > After closing the chatbot window and opening it again the former messages are still there. This might be a security issue (e.g. in an internet cafe etc.) I have no idea if it would be possible to delete the messages if the user closes the widget? Or we should ask an expert if this is necessary or not.
> > 
> > 
> > > 
> > 
> > 
> > > @SGrueber To delete the history upon closing the parameter "clearChatOnReload" in "chatWindow" needs to be true.
> > 
> > 
> > @714Lemons Should we enable this in our demo integration or leave it as it is and it can be changed in customer projects if wanted?
> 
> @shauke Leave it as it is.

I agree with @shauke, leave it as it is. We have the same behavior on our website, so hopefully it is no security issue.

2025-02-21 10:41 UTC, shauke commented on src/assets/i18n/fr_FR.json
> +  "copilot.footer.company": "Politique de confidentialité",
This is the place where the `copilot.footer.company` value is rendered.
![image](https://github.com/user-attachments/assets/abd9da4f-33a5-4577-9573-5f6351a6c05d)

2025-02-21 10:59 UTC, shauke commented
> Please check the font family of the Intershop Copilot for our PWA. The PWA uses Roboto, but the copilot uses Open Sans.

@iwiederhold The used font we cannot changed from the PWA integration. This needs to be changed in the Copilot Chat Embed project by @714Lemons .

2025-02-21 14:17 UTC, mglatter submitted a review, later dismissed

2025-02-21 14:17 UTC, mglatter commented on src/assets/i18n/fr_FR.json
> +  "copilot.footer.company": "Politique de confidentialité",
So, ideally it should probably match, but "Notes sur la protection des données" would be too long here, and the current translation conveys the same idea. So we can leave it.

2025-02-24 08:16 UTC, shauke commented on src/app/extensions/copilot/store/copilot-config/copilot-config.selectors.ts
> +export const getCopilotConfig = createSelector(getCopilotState, state => state?.copilotConfig);
done

2025-02-24 22:53 UTC, shauke approved these changes

2025-02-24 23:04 UTC, merged