Docs: update accessibility documentation
intershop/intershop-pwa pull request #1700
Opened 2024-07-17 14:42 UTC by LucasHengelhaupt

## PR Type

[x] Documentation content changes

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2024-08-01 13:14 UTC, SGrueber requested changes
it looks good, we only need an improved introduction (see below)

2024-08-01 13:14 UTC, SGrueber commented on docs/guides/accessibility.md
> +## Check the Accessibility of a Page
The text above doesn't fit to the new content of this documentation. (Most of the ... npm run lint)
- Start with a general motivation, the 1st sentence is good, maybe you can mention the guidelines ....
- move the lint part to the Eslint Rules section (only what is needed)

2024-08-01 13:14 UTC, SGrueber commented on docs/guides/accessibility.md
> +The following list are some suggestions of free tools that have been used to check the accessibility of the PWA:
suggestion: 'The following list contains some suggestions'

2024-08-01 13:14 UTC, SGrueber commented on docs/guides/accessibility.md
> +With the current technology, automated tools can only check for around 25-30% of the WCAG criteria.
explain in the introduction what are WCAG criteria

2025-03-18 11:10 UTC, SGrueber submitted a review, later dismissed

2025-03-21 12:26 UTC, marschmidt89 approved these changes

2025-03-21 12:35 UTC, andreassteinmann submitted a review, later dismissed

2025-03-25 13:46 UTC, merged