feat: add tax type settings for budgets (#99165)
intershop/intershop-pwa pull request #1715
Opened 2024-09-24 08:03 UTC by skoch-intershop

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

Issue Number: Closes #99165

## What Is the New Behavior?

As an B2B customer account admin
I want to configure if budgets are meant net or gross in order to work closer to my companies processes and therefore more efficient. This setting will apply for both user and cost center budgets and is a setting on customer level.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

requires ICM version higher than 12.2.

[AB#99862](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/99862)

2024-12-10 10:41 UTC, M-Behr requested changes
I ordered in gross ($ 2,307.45) and set it to net ($ 1,939.03) afterwards:
- Cost Center Approval displays gross by "including this order".
- Display in progress bar is not updated.
<img width="643" alt="{4440CF04-F458-42A5-8CB1-E2B4AB9A889F}" src="https://github.com/user-attachments/assets/7336b704-c30b-4223-95fb-473dba5208d7">

Click on term "Gross" or "Net" triggered the confirmation dialog, but the radio button is not selected. After confirmation: Success message appears, but option remains unchanged.
<img width="505" alt="review_budget_clickarea" src="https://github.com/user-attachments/assets/472b2bde-5572-40eb-b9fe-622c89f5ddd7">

2024-12-10 13:34 UTC, iwiederhold commented
Is there another solution for the truncated tooltip in the mobile view?

![image](https://github.com/user-attachments/assets/4ee57fb3-b448-41e9-b47c-b26fd56a1932)

2024-12-11 07:49 UTC, M-Behr commented
> Is there another solution for the truncated tooltip in the mobile view? Maybe to the bottom left?
> 
> ![image](https://private-user-images.githubusercontent.com/38127411/394294007-4ee57fb3-b448-41e9-b47c-b26fd56a1932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDM1NjksIm5iZiI6MTczMzkwMzI2OSwicGF0aCI6Ii8zODEyNzQxMS8zOTQyOTQwMDctNGVlNTdmYjMtYjQ0OC00MWU5LWI0N2MtYjI2ZmQ1NmExOTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA3NDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMjdmNjBiYjg1ZWNlNTRiYzk4YzY3MDZiMTU3YzBiNzI5YWMwMDk4MjIyNDNhNTM1MmI2MTFjMTQ2YzIzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vVw7g7U6DTJI_noN5ksQAmcOrvLHO-WFZ4NMxMcndUs)

The popover can be opened in another direction.

2024-12-11 11:40 UTC, skoch-intershop reviewed
No complaints.

2024-12-11 12:43 UTC, M-Behr approved these changes
Works really well - great job! 💯

2024-12-11 12:56 UTC, iwiederhold approved these changes
THX for the good cooperation!

2024-12-13 07:38 UTC, SGrueber submitted a review, later dismissed

2025-01-20 13:20 UTC, merged