feat: Requisition Management / Order Approval functionality
intershop/intershop-pwa pull request #326
Opened 2020-07-15 07:04 UTC by shauke

**:moneybag: Order Approval | Basic Requisition Management Project**

The basic order approval management functionality in the my account section needs to be implemented as a sub-project to the PWA core (with feature toggle?).

- [x] `requisition-management` project
- [ ] routing
- [ ] requisition model
- [ ] state management / facade
- [ ] service
- [ ] permission checks
- [ ] unit testing
- [ ] feature or configuration toggle?

*Notes*
- direct routing/browser refresh support
- requisitions state as part of the customer state that would automatically take care of cleaning the store on logout?
- list REST call for listings, details call only for the selected details view

## PR Type

[x] Feature

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2020-10-15 12:44 UTC, iwiederhold requested changes

2020-10-15 12:44 UTC, iwiederhold commented on projects/requisition-management/src/app/components/requisition-summary/requisition-summary.component.html
> +
Approval Badges

Please use other badges for the approval status: 
<span class="badge badge-success">Success</span> for APPROVED
<span class="badge badge-danger">Danger</span> for REJECTED
<span class="badge badge-warning">Warning</span> for PENDING

2020-10-15 14:38 UTC, M-Behr requested changes
The basic functionality works really good. Thanks for the great teamwork! 👍 

I found some minor issues:
![Requisition Details](https://user-images.githubusercontent.com/66066967/96142415-58da8800-0f02-11eb-917e-2d270b0144ca.png)
Requisition Details:
- rename heading in Requisition Details
- remove pending status of last approver => it is needed, when cost center approval is implemented => then this "Approver(s): Conny Kitera (approved), Ralf Ulitzsch (pending)" is possible and then the user should know who has already approved and who has not

![Order Details_Anpassungen](https://user-images.githubusercontent.com/66066967/96142479-6d1e8500-0f02-11eb-9e2a-1c04c5c50c91.png)
Order Details:
- some little adaptions: Order Number => Order No.; missing badge
- remove blank characters next to brackets

![Order History vs Requisitions](https://user-images.githubusercontent.com/66066967/96143469-67756f00-0f03-11eb-8ff4-f01ce80167c3.png)
Phone View:
- ":" is missing after labels
- differences between order list and requisition/approval lists => order total is displayed in first row/last row (My mistake! Sorry! I thought this did not fit into the first row.); also the spaces between lines are different => Can we unify this? I suggest: Order total in first line (like order history) and smaller spaces between lines (like requisitions and approvals)

ToDo's for later:
- add amount of rows (items) in other tables, e.g. order history, order templates, quoting, users.
- redesign budgets in buyer approval

2020-10-16 13:07 UTC, SGrueber commented
To improve the responsive design of the order list is not part of this story. You can find a card for it in the technical debts project.

2020-11-12 11:59 UTC, M-Behr requested changes
The functionality works very well and the feature looks great! 👍 
I found only some naming convention issues and some inconsistencies:

**Checkout - Approval Details Dialog**
- missing sentence points when listing the conditions

**Approval / Requisition List**
- missing colons after label in phone view

**Approval / Requisition Details**
- "Date of Approval :" => "Date of Approval:" _(space character between word & colon)_
- if approved => order total is displayed in already spent bar, so no additional bar is needed in the diagram (this is also the reason why this "including this order" is not displayed in approved case)
- "Monthly budget:" => "Budget (monthly)" _(only for consistency reasons, see user management)_

**User Management - Popover for bar diagram**
- Labels in title case
- $ is missing for spent value
- "Monthly spend limit" => "Budget (monthly)"
- "spent" => "Already Spent" _(only for consistency reasons, see buyer approval)_

**User Management - User Details**
- "Budget (monthly) :" => "Budget (monthly):" _(space character between word & colon)_
- "No order spend limit defined." and "No budget defined." or use "Unlimited" by both _(currently it is a mix between these both possibilities)_

**User Management - Edit Budget**
- USD => $ _(only for consistency reasons)_

2020-11-12 12:34 UTC, shauke reviewed
- [x] requisition submission is not showing a loading animation for the whole process (the two combined POST REST calls), its only loading for the validation and after this it might take some time before the requisition is actually finished but one is not getting feedback of this ongoing process
![image](https://user-images.githubusercontent.com/50741106/98842562-0bdaca80-244a-11eb-8dbb-590ef97a2145.png)

2020-11-18 08:29 UTC, M-Behr requested changes
Some points are still open from the last review (see the checklist in my last comment).
There are some new issues on the User Management page:

- [x] The "Budget:" label is missing in case of unlimited. => add the label
- [x] The "Unlimited" value is displayed left. => move it to right
- [x] "Budget (weekly)::" => "Budget (weekly):" _(duplicate colons)_
![User Management](https://user-images.githubusercontent.com/66066967/99504918-77f48b80-2980-11eb-96c5-1a40e9972ed6.png)

2020-11-18 10:26 UTC, iwiederhold submitted a review, later dismissed

2020-11-20 14:14 UTC, M-Behr requested changes
These points are still open:
 - [x] "Date of Approval :" => "Date of Approval:" _(remove space character between word & colon)_
 - [ ] "Budget (monthly) :" => "Budget (monthly):" _(remove space character between word & colon)_

![Approval details](https://user-images.githubusercontent.com/66066967/99809510-af129a80-2b42-11eb-8800-d90b7f1ae05c.png)

2020-11-23 19:47 UTC, shauke reviewed
The overall functionality and implementation looks fine, only a few small things to improve. 👍

2020-11-23 19:47 UTC, shauke commented on projects/requisition-management/src/app/store/requisitions/requisitions.reducer.ts
> +  )
The `unsetLoadingAndErrorOn` function should be used.

2020-11-24 08:15 UTC, shauke commented on projects/requisition-management/src/app/exports/lazy-checkout-receipt-requisition/lazy-checkout-receipt-requisition.component.ts
> +}
After talking to Max the `lazy-checkout-receipt-requisition` component should be removed.

2020-11-25 08:55 UTC, SGrueber commented on src/app/core/store/customer/basket/basket.reducer.ts
> +    info: undefined,
this has nothing to do with this branch, only submittedBasket has been added

2020-11-25 09:05 UTC, SGrueber commented on projects/requisition-management/src/index.html
> +    <title>Requisition Management</title>
as long as we cannot use the requisition management as standalone project is doesn't matter

2020-11-30 16:09 UTC, M-Behr submitted a review, later dismissed
Good job! 👍

2020-12-17 13:38 UTC, merged