SSO with Auth0
intershop/intershop-pwa pull request #352
Opened 2020-07-29 19:47 UTC by dhhyi

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2020-11-30 15:25 UTC, MaxKless reviewed
Code looks good, will do more testing next

2020-11-30 15:39 UTC, dhhyi commented on docs/concepts/sso.md
> +- PWA
👍

2020-11-30 15:39 UTC, dhhyi commented on docs/guides/sso-auth0.md
> +```
👍

2020-12-01 10:47 UTC, MaxKless requested changes
![image](https://user-images.githubusercontent.com/34165455/100730294-2c9f9b80-33ca-11eb-8d77-40d61ff942bb.png)
I ran into this issue when using multiple channels that share a user (see multi channel configuration at the bottom). 
**Steps to reproduce:**
- go to pwa.net/de
- sign in using Auth0
- navigate to pwa.net/us
- log out 
-> see the error above. The logout still works and when you go back to the pwa, you are logged out. 

**Configuration**

```
# export appropriate ICM_BASE_URL and use with
# docker-compose -f templates/docker-compose.yml up --build

version: '3'
services:
  pwa:
    build:
      context: ..
      args:
        # configuration: local
        configuration: production
        serviceWorker: 'false'
    environment:
      - LOGGING=on
      - ICM_BASE_URL
      # - PROXY_ICM=true
      - TRUST_ICM=true
      # - PROMETHEUS=on
      - IDENTITY_PROVIDERS={"Auth0":{"type":"auth0","domain":"dev-9pqwi8uh.eu.auth0.com","clientID":"V2xvLUo3YSfGdCmJz7u381dSevoVkOso"}}
  nginx:
    build: ../nginx
    depends_on:
      - pwa
    environment:
      UPSTREAM_PWA: 'http://pwa:4200'
      # DEBUG: 1
      CACHE: 0
      PAGESPEED: 0
      # PROMETHEUS: 1
      # COMPRESSION: 0
      # DEVICE_DETECTION: 0
      # MULTI_CHANNEL_SOURCE: env:///ASDF?type=application/yaml
      MULTI_CHANNEL: |
        .+\.net:
            - baseHref: /de
              lang: de_DE
              channel: inSPIRED-inTRONICS-Site
              identityProvider: Auth0
            - baseHref: /us
              lang: en_US
              channel: inSPIRED-inTRONICS-Site
              identityProvider: Auth0
        .+\.de:
            channel: inSPIRED-inTRONICS-Site
            lang: de_DE
            identityProvider: Auth0
        .+\.com:
            channel: inSPIRED-inTRONICS_Business-Site
            features: quoting,businessCustomerRegistration,advancedVariationHandling
            theme: "blue|688dc3"
        .+\.fr:
            channel: inSPIRED-inTRONICS-Site
            lang: fr_FR
            application: smb-responsive
            features: quoting
            theme: "blue|688dc3"

    ports:
      - '4200:80'
      # - '9113:9113'

```

2020-12-02 08:35 UTC, dhhyi commented
>       MULTI_CHANNEL: |
>         .+\.net:
>             - baseHref: /de
>               lang: de_DE
>               channel: inSPIRED-inTRONICS-Site
>               identityProvider: Auth0
>             - baseHref: /us
>               lang: en_US
>               channel: inSPIRED-inTRONICS-Site
>               identityProvider: Auth0

The error you see comes from the Auth0 configuration, because `/us` routes are not configured to be valid URLs. This has to be done in the Auth0 backoffice.

What would be your expectation at this point?

2020-12-02 08:45 UTC, marschmidt89 submitted a review, later dismissed
documentation review done

2020-12-03 09:17 UTC, MaxKless approved these changes

2020-12-03 11:39 UTC, merged