fix: display only one validation error for a form element at once
intershop/intershop-pwa pull request #458
Opened 2020-11-12 11:46 UTC by SGrueber

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
Multiple validation error messages are shown for one form element, 
e.g. if an email address is required 2 errors are shown, if the field is empty

Issue Number: Closes #

## What Is the New Behavior?
If a form element has several validators, only the 1st validation message is shown

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2020-11-23 11:51 UTC, dhhyi requested changes

2020-11-23 11:51 UTC, dhhyi commented on src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.html
> +  </ng-container>
` | slice:0:1`

2020-11-23 11:53 UTC, dhhyi commented on src/app/shared/forms/components/form-control-feedback/form-control-feedback.component.html
> +  </ng-container>
I don't quite understand why `async` is used on `e$` here. It should be the errors array that should be subscribed to.

2020-11-23 18:12 UTC, SGrueber commented
I understand the async at e$ neither, but it is only working that way, all other solutions gave compiler errors

2020-11-23 18:33 UTC, dhhyi commented
> I understand the async at e$ neither, but it is only working that way, all other solutions gave compiler errors

ah yes, I misread the declaration.
I think you can safely use translate.instant here to get rid of subscriptions.

2020-11-23 18:35 UTC, dhhyi commented
> > I understand the async at e$ neither, but it is only working that way, all other solutions gave compiler errors
> 
> ah yes, I misread the declaration.
> I think you can safely use translate.instant here to get rid of subscriptions.

Or even better: don't do the translation in the component and do it on the template with translate pipe.

2020-12-02 08:29 UTC, dhhyi approved these changes
👍

2020-12-02 08:47 UTC, merged