fix: prevent error if language switched on order details page
intershop/intershop-pwa pull request #459
Opened 2020-11-12 13:33 UTC by SGrueber

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
After the user changed the language on the order details page an error page is displayed. - This problem only occurs in case of server-side rendering with Angular Universal.

see also IS-IS-31347

## What Is the New Behavior?
The order detail page is displayed in the requested language.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2020-11-12 16:09 UTC, shauke requested changes

2020-11-12 16:09 UTC, shauke commented on src/app/core/store/customer/orders/orders.effects.ts
> +      )
Looks good once you get rid of the two unnecessary line breaks. ;)

2020-11-13 02:46 UTC, dhhyi approved these changes
LGTM 👍

2020-11-16 08:13 UTC, shauke approved these changes

2020-11-16 08:36 UTC, merged