Style/style improvements
intershop/intershop-pwa pull request #460
Opened 2020-11-17 09:07 UTC by SGrueber

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
There are several ui related issues.

Issue Number: Closes #

see ISREST-982, ISREST-1027, ISREST-1029, ISREST-1031, ISREST-1048, ISREST-1053 

## What Is the New Behavior?
The placement of the wishlist header not has been improved.
Action icons are visible on product detail page in mobile view.
The placement of the line item action icons has been improved.
The add-to-cart button is not visible on order template details page, if the order template is empty.
The disabled secondary button has no hover effects any more.
The add-to-cart buttons are disabled on quick order page if the form is invalid or empty.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2020-11-17 14:06 UTC, iwiederhold requested changes
Hi, I've found two little styling bugs. (see screenshots)

![icons_not_in_line](https://user-images.githubusercontent.com/38127411/99399832-79717580-28e6-11eb-823d-3226eb64f8dc.jpg)

![IMG_2919](https://user-images.githubusercontent.com/38127411/99497093-ae78d900-2975-11eb-8272-1cf84d916dbf.jpg)

2020-11-17 15:48 UTC, M-Behr requested changes
Please remove the "add to cart" icon of an empty order template in the list, too (see ISREST-1048).
![Order Templates list](https://user-images.githubusercontent.com/66066967/99411948-7aa99f00-28f4-11eb-9398-2dc87f9d85da.png)

2020-11-20 14:01 UTC, M-Behr submitted a review, later dismissed

2020-11-23 11:46 UTC, iwiederhold approved these changes

2020-11-23 13:01 UTC, M-Behr approved these changes

2020-11-24 15:18 UTC, shauke approved these changes

2020-11-24 15:18 UTC, shauke commented on src/app/extensions/order-templates/pages/account-order-template-detail/account-order-template-detail-page.component.html
> +    *ngIf="orderTemplate.itemsCount && orderTemplate.itemsCount > 0"
Isn't this a place for an elvis operator?

2020-11-25 07:57 UTC, merged