explore/formly-integration
intershop/intershop-pwa pull request #485
Opened 2020-12-09 15:20 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-02-09 15:05 UTC, M-Behr requested changes
Good work! :) For the most part, it works as before.

I found some issues:
- [ ] only country is marked as required field on address form (e.g. registration page, my account, checkout)
- [ ] font size of error messages and position of validation icons on select boxes (cross overlaps arrow)
- [ ] display first form hint and below error message (e.g. select United States and see "APO/FPO" link) => Your order is also possible but if we rework it step by step, I would like to avoid inconsistencies. Please stay with the current order.
![FormValidation](https://user-images.githubusercontent.com/66066967/107371099-26bde900-6ae4-11eb-80ae-8a0f051c6bc0.png)

- [ ] contact us form is not responsive => please align labels top
- [ ] form hint for comment "Your message: 30000 characters remaining." is missing 
- [ ] submit button is not in line with the form fields

- [ ] add address in checkout does not work => error message: customer.address_not_found.error => I think the functionality tries to change the selected address instead of create a new address.
**Current behavior:** click "add address" link, enter a new address and click "save changes" => error
**Expected:** click "add address" link, enter a new address and click "save address" => address is created and selected as invoice or shipping address.

- [ ] Taxation ID is displayed twice on b2b registration form
- [ ] Taxation ID is part of address template in my account/checkout?

I think we need to achieve a very flexible address template. I noted down that we separated the registration page in 3 sections: Company Information, Personal Information and Address.
For the address template in my account/checkout, we use company name 1 and 2 from company information and the address component. I created this page after our last discussion with the team:
![Address Template Rework](https://user-images.githubusercontent.com/66066967/107379692-79e86980-6aed-11eb-924f-94a3a7060904.png)

2021-02-09 15:51 UTC, dhhyi requested changes
Part 1:
- mainly focused on contact-us
Later:
- duplications in adressform models could be reduced. I'll propose a suggestion.

2021-02-16 11:35 UTC, M-Behr requested changes
Hi Max,
your integration looks pretty good.

I found a little little thing in the registration form validation:
- [ ] Please display the error message in a new line (not next to the hint).
![2021-02-16 10_32_20-Register _ Intershop PWA](https://user-images.githubusercontent.com/66066967/108055203-f3350e80-704f-11eb-9cf6-837f425c6818.png)

And I found some crazy behavior on the address page in checkout. It took me a little more research to figure out why this was happening.
- [ ] Edit an address in the checkout. Save the changes and the edited address is displayed. All is fine. If you now click again the edit icon an empty address form is displayed and for the add address an prefilled address form is displayed. The forms are mixed up.

2021-02-16 15:35 UTC, iwiederhold submitted a review, later dismissed

2021-02-17 15:35 UTC, marschmidt89 submitted a review, later dismissed
Documentation review done.

2021-02-19 10:00 UTC, dhhyi requested changes

2021-02-19 10:09 UTC, dhhyi commented on src/app/shared/formly-address-forms/configurations/default/address-form-default.configuration.ts
> +    };
why even pick 'mainDivisionCode'? It should be unusable, if the country changed 🤔

2021-02-22 09:25 UTC, dhhyi submitted a review, later dismissed

2021-02-22 14:13 UTC, M-Behr approved these changes

2021-02-22 15:55 UTC, SGrueber approved these changes

2021-02-22 15:56 UTC, merged