Feature/Display purchaser box
intershop/intershop-pwa pull request #486
Opened 2020-12-11 11:49 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
There is no purchaser info on checkout and order details page.

Issue Number: Closes #

## What Is the New Behavior?
There is a purchaser box on checkout review, checkout receipt and order details page. 
The basket model service and NgRx store has been extended by methods to add, update and delete custom attribute on the basket,

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2020-12-16 16:42 UTC, shauke submitted a review, later dismissed

2020-12-16 16:46 UTC, M-Behr requested changes
Please rename the headline from Purchaser to Buyer (only for consistent naming).
Could you please check if the order of the data still matches in the e-mail? The buyer box has already been added to the e-mails with the approval feature.

2020-12-16 16:57 UTC, shauke commented
PWA
![image](https://user-images.githubusercontent.com/50741106/102380239-f8ca9580-3fc7-11eb-8d21-650545a02532.png)

E-Mail
![image](https://user-images.githubusercontent.com/50741106/102380428-32030580-3fc8-11eb-9993-4b155634e808.png)

2020-12-17 10:13 UTC, M-Behr approved these changes

2020-12-17 14:19 UTC, shauke approved these changes

2020-12-17 14:23 UTC, merged