feat: environment specific component overrides
intershop/intershop-pwa pull request #537
Opened 2021-02-07 20:19 UTC by dhhyi

## PR Type

[x] Feature
[x] Refactoring (no functional changes, no API changes)
[x] Build-related changes

## What Is the Current Behavior?

The current customization concept for components does not support having multiple brands.
There is Multi-Theme support, but not everything can be handled that way.
Using custom components supports being upgradable while only supporting one override per source repository.

## What Is the New Behavior?

- HTML templates and Component Styles can be replaced by Angular CLI environment option using custom webpack build.
- refactored setting production mode to support running Angular CLI with multiple configurations
  - `ng serve -c brand,production`
  - not supported with the previous way as fileReplacements are not merged but also overridden

## Does this PR Introduce a Breaking Change?

[x] Yes
[ ] No

## Other Information

2021-02-17 15:49 UTC, shauke requested changes
Without the last commit "feat: adding overrides for a brand" - I assume that was just a temporary showcase commit - the changes are almost fine (see minor comments).

2021-02-17 16:21 UTC, shauke commented
Is there anything that would be worth a migration note, e.g. the Breaking Changes? Maybe in regards to the `production` configuration changes?

2021-02-18 08:54 UTC, dhhyi commented on purgecss.config.js
> +  safelist: [/(p|m)(l|r|x|y|t|b)?-[0-5]/],
yes, utilities for padding and margin

2021-02-18 08:54 UTC, dhhyi commented on purgecss.config.js
> +};
I guess you can decide that when working on that ticket 😉

2021-02-18 08:55 UTC, dhhyi commented on docs/check-dead-links.js
> +          !link.includes('docs.intershop.') &&
Recently support sites are frequently unavailable. This should not give us red builds.

2021-02-18 09:20 UTC, shauke commented on purgecss.config.js
> +};
Okay, that is a good idea. 👍

2021-02-18 09:33 UTC, shauke approved these changes

2021-02-18 10:31 UTC, shauke approved these changes

2021-02-18 10:41 UTC, merged