refactor: use native swiper instead of ngx-swiper-wrapper
intershop/intershop-pwa pull request #552
Opened 2021-02-16 16:10 UTC by dhhyi

## PR Type

[x] Refactoring (no functional changes, no API changes)

## What Is the Current Behavior?

ngx-swiper-wrapper is used in the PWA but it will not be supported any longer (see migration note for link).

## What Is the New Behavior?

- native swiper usage
- swiper only imported in page modules which reduces main bundle size.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-02-17 18:03 UTC, shauke requested changes
Before
![image](https://user-images.githubusercontent.com/50741106/108247152-93735c00-7152-11eb-85b1-b6fe5038cf04.png)

After
![image](https://user-images.githubusercontent.com/50741106/108247230-ab4ae000-7152-11eb-81b9-e130a74377ab.png)

The controls for click slide switching are missing. Swiping with mouse drag & drop works though (meaning the Swiper is initialized).

2021-02-18 10:29 UTC, dhhyi commented on src/app/pages/product/product-links/product-links.component.ts
> + * For the carousel swiper is used. Specific configuration for product link carousels have to be done here.
Yes, I moved this to the component so it can be done directly where it's needed.

2021-02-18 10:32 UTC, dhhyi commented on src/app/core/appearance.module.ts
> -
It looks like it's no longer possible to do it the same way as before. Most of those defaults are probably defaults for swiper anyway. I think it's better to supply all configuration where it's needed.

2021-02-24 14:36 UTC, suschneider approved these changes

2021-02-24 21:42 UTC, shauke approved these changes

2021-02-24 21:43 UTC, merged