feat: add order template details links on order template widget
intershop/intershop-pwa pull request #575
Opened 2021-02-24 17:09 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the New Behavior?
On the order template widget the names of the order templates are linked to the corresponding order template detail pages now.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-02-24 20:10 UTC, shauke requested changes

2021-02-24 20:10 UTC, shauke commented on src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.html
> +            }}</a>
This is not how we should create such links (even though we have done it in the past).
This is the way to go:
```
<a [routerLink]="['/account/order-templates', orderTemplate.id]" class="text-decoration-none">{{
      orderTemplate.title
}}</a>
```

2021-02-25 07:49 UTC, SGrueber commented on src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.spec.ts
> +    { id: '1', title: 'order template ' },
The space was intended to make the snapshot more readable, but if it made you wonder .... I removed it

2021-02-26 09:05 UTC, shauke commented on src/app/extensions/order-templates/shared/order-template-widget/order-template-widget.component.spec.ts
> +    { id: '1', title: 'order template ' },
Yes I would vote for more readable IDs than Snapshots. The Snapshots are really not so much for us to read. ;)

2021-02-26 09:06 UTC, shauke approved these changes

2021-02-26 11:37 UTC, merged