fix: prevent toast styles purging
intershop/intershop-pwa pull request #601
Opened 2021-03-05 19:06 UTC by dhhyi

## PR Type

[x] Bugfix

## What Is the Current Behavior?

- toast styles are removed by PurgeCSS

Issue Number: Closes #600 

## What Is the New Behavior?

- toast styles are kept

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

relates to #562

2021-03-08 08:57 UTC, shauke requested changes
The issue is not completely fixed yet. The error toast hast still styling issues.

Current state:
![image](https://user-images.githubusercontent.com/50741106/110298097-76fd6d80-7ff4-11eb-8a7d-77fe3fe3584c.png)

The way it was and should be:
![image](https://user-images.githubusercontent.com/50741106/110298169-96949600-7ff4-11eb-8a8c-d7dc5be26027.png)

2021-03-08 11:12 UTC, shauke commented
![image](https://user-images.githubusercontent.com/50741106/110313875-5ee31980-8007-11eb-8719-67155e3bbbf9.png)

This could be another missing styling after purgecss issue.

2021-03-08 16:22 UTC, M-Behr commented
The tabs in the My Account section are also affected. Please take a look at this as well. Maybe it has the same cause.
![screenshot-intershoppwa-b2b azurewebsites net-2021 03 08-17_10_02](https://user-images.githubusercontent.com/66066967/110349002-8b605b00-8032-11eb-865d-b6879d2c816a.png)

2021-03-18 18:12 UTC, shauke approved these changes

2021-03-19 12:58 UTC, merged