feat: replace any typescript file by configuration
intershop/intershop-pwa pull request #616
Opened 2021-03-12 13:47 UTC by dhhyi

## PR Type

[x] Feature

## What Is the Current Behavior?

Environment specific overrides (#537) can only override HTML templates and component styles

## What Is the New Behavior?

Any typescript file can be overridden by having the extension "<key>.ts".

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

This is useful for projects for overriding functionality without introducing changes in ISH sources.

2021-03-19 12:44 UTC, shauke requested changes
Nice feature, but some additional documentation would be nice too. ;)

2021-03-19 20:45 UTC, dhhyi commented
> Nice feature, but some additional documentation would be nice too. ;)

Okay 😄

2021-03-20 10:36 UTC, dhhyi commented
I took the opportunity to also sneak in an optimization and a test. 👍

2021-03-24 13:17 UTC, shauke approved these changes

2021-03-24 13:19 UTC, merged