feat: modal on sso navigation
intershop/intershop-pwa pull request #647
Opened 2021-04-06 12:36 UTC by MaxKless

## PR Type

[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
Currently, you can navigate away from the registration page during sso account completion and break the process.

Issue Number: Closes #640

## What Is the New Behavior?
Now, there exists a modal that asks you to confirm whether you want to leave the sso account completion. Doing this will log you out and ensure a proper state.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-04-06 12:38 UTC, MaxKless commented
Hi @marschmidt89 , please provide translations / proper text for the new translation keys:
 "account.register.confirm_leave_modal.body"
  "account.register.confirm_leave_modal.cancel_button"
  "account.register.confirm_leave_modal.confirm_button"
  "account.register.confirm_leave_modal.title"

2021-04-07 09:23 UTC, M-Behr requested changes
Hi Max, I have some feedback regarding the modal:

- [ ]  I would like to change the text a little bit, e.g. remove punctuation in heading and shorter button names to avoid breaks. See attachment.
- [x] The secondary button has incorrect styling. (I think it should be: class="btn btn-secondary")
- [ ] The button order does not follow our pattern.
- [ ] The form in the background moves, if I triggered cancellation via click on logo. See here:
![background](https://user-images.githubusercontent.com/66066967/113842590-18621580-9793-11eb-8617-366938e41022.png)

Here is my suggestion for this modal:
![IAD_CancelSSOREgistration](https://user-images.githubusercontent.com/66066967/113842632-231caa80-9793-11eb-9643-249460a1d0fe.png)

2021-04-12 11:37 UTC, M-Behr approved these changes
If you could hide the error message when changing the language, that would be great. Otherwise I'll write an extra ticket for it. The modal looks good. Translations should be adjusted again. Thank you!

2021-04-26 08:08 UTC, jometzner requested changes

2021-04-26 08:08 UTC, jometzner commented on src/app/pages/registration/registration-page.component.ts
> +    this.options = this.registrationFormConfiguration.getRegistrationFormConfigurationOptions(
Kind of lengthy, wordy and redundant. Could you rename the method into just `getOptions()`?

2021-04-26 08:08 UTC, jometzner commented on src/app/pages/registration/registration-page.component.ts
> +      userId: route.queryParams.userid,
userid query param is now mandatory for all routes that include `sso`, am I right? Should this be documented?

2021-04-26 08:08 UTC, jometzner commented on src/app/pages/registration/registration-page.guard.ts
> +    return this.registrationConfigurationService.canDeactivate(component.extractConfig(currentRoute));
I like the simplicity of this. Nice work.

2021-04-26 10:38 UTC, MaxKless commented on src/app/core/facades/account.facade.ts
> +  setRegistrationInfo(registrationInfo: {
The type existed, I just forgot about it: SsoRegistrationType

2021-04-26 11:09 UTC, MaxKless commented on src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
> +              switchMap(modalRef => race(modalRef.dismissed.pipe(mapTo(false)), from(modalRef.result))),
the modalRef delivers whatever we define for the close method in the modal itself. My implementation works only with booleans but you could put anything in there.

2021-04-26 11:15 UTC, MaxKless commented on src/app/core/identity-provider/auth0.identity-provider.ts
> +                    navigated || navigated === null
It's null if we refresh the registration page during the sso process. Usually I would test for undefined or null as `!navigated` but here I'm just trying to catch one specific case.

2021-04-27 07:37 UTC, jometzner commented on src/app/core/services/registration-form-configuration/registration-form-configuration.service.ts
> +              switchMap(modalRef => race(modalRef.dismissed.pipe(mapTo(false)), from(modalRef.result))),
Right, I've found that answer yesterday once I came across your changes to `confirm-leave-modal`

2021-04-27 07:52 UTC, jometzner requested changes

2021-04-27 07:52 UTC, jometzner commented on src/app/pages/registration/registration-page.component.ts
> +    this.fields = this.registrationFormConfiguration.getRegistrationFormConfiguration(this.registrationConfig);
Somehow this is still bothering me. It's only naming! But I would prefer to read this line like this:
```
this.fields = this.registrationFormConfiguration.getFields(this.registrationConfig);
```

2021-04-27 08:36 UTC, jometzner approved these changes

2021-04-27 08:54 UTC, merged