feat:Implement save for later checkbox for cybersource credit card.
intershop/intershop-pwa pull request #703
Opened 2021-05-19 04:19 UTC by rinkeshrsys

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

The checkbox was not implemented for Save for later feature for Cybersource Credit Card.

## What Is the New Behavior?

A Cybersource credit card can be saved for later usage on the user's account.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-28 14:28 UTC, SGrueber commented
Pls, rebase this branch and use the component <ish-payment-save-checkbox> to render the safe-for-later checkbox. See also how to use it in the other payment components

2021-09-22 06:37 UTC, SGrueber requested changes
The branch is still not based on a PWA 1.0+ - rebasing the branch and upgrading your development environment is necessary. Pls find the release notes here: https://github.com/intershop/intershop-pwa/releases

2021-09-22 06:37 UTC, SGrueber commented on src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.ts
> +    this.cyberSourceCreditCardForm = new FormGroup({ saveForLater: new FormControl(true) });
this change is not necessary - creating an empty FormGroup is enough, the saveForLater FormControl is added by the PaymentSaveForLater component itself, see also PaymentPayoneCreditCardComponent

2021-09-22 06:37 UTC, SGrueber commented on src/app/pages/checkout-payment/payment-cybersource-creditcard/payment-cybersource-creditcard.component.ts
> +    if (this.cyberSourceCreditCardForm.get('saveForLater')) {
Is resetErrors() needed here?

2021-12-08 05:00 UTC, harshrsys commented
This feature has been merged under PR (https://github.com/intershop/intershop-pwa/pull/925). We can delete this PR and branch.

2021-12-08 08:00 UTC, closed without merging