feat: enable the b2b customer to enter an order reference id during checkout
intershop/intershop-pwa pull request #714
Opened 2021-06-01 15:35 UTC by SGrueber

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #697

## What Is the New Behavior?
On the checkout shipping page the b2b user has the possibility to enter an order reference id. This id is is shown on the buyer widget of the checkout review, checkout receipt and order detail page.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-06-02 06:32 UTC, iwiederhold submitted a review, later dismissed
Please check this behavior:
If the user wants to update this ID in a last checkout step (Review Page), he can click on the pencil icon. Then he cames on the Shipping Page again. He edits the ID again and wants to APPLY this. --> ERROR Page

2021-06-02 12:41 UTC, M-Behr requested changes
- Server time out error when editing input field and click "Apply" again
- keep it empty and click "Apply" => error message is displayed below "Shipping" but it should be displayed below "Enter an Order Reference ID"
- typo in success message: order reference id => order reference ID

2021-06-10 11:31 UTC, M-Behr approved these changes
It works fine 👍

2021-06-11 10:30 UTC, shauke approved these changes

2021-06-14 06:46 UTC, merged