chore: adapt demo multisite config
intershop/intershop-pwa pull request #715
Opened 2021-06-02 06:01 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-06-03 15:54 UTC, dhhyi requested changes

2021-06-03 15:54 UTC, dhhyi commented on nginx/multi-channel.yaml
> +  - baseHref: /en
please don't change anything here. This is supposed to be the working default for the multi channel.

2021-06-08 15:05 UTC, marschmidt89 submitted a review, later dismissed
documentation review done

2021-06-15 11:37 UTC, shauke approved these changes

2021-06-16 07:30 UTC, shauke approved these changes

2021-06-16 07:32 UTC, merged