refactor: use cdk tables to display lists
intershop/intershop-pwa pull request #743
Opened 2021-06-22 11:50 UTC by SGrueber

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-06-25 14:21 UTC, M-Behr requested changes
The table header styling was changed and the table header should be hidden on phone view. The changes also occurs in the case of requisitions and approvals. Maybe it is a general styling issue.
Desktop:
![2021-06-25 16_11_07-My Account _ Intershop PWA](https://user-images.githubusercontent.com/66066967/123438460-009b7000-d5d1-11eb-92d1-545da533fbad.png)
Phone:
![2021-06-25 16_11_32-My Account _ Intershop PWA](https://user-images.githubusercontent.com/66066967/123438500-08f3ab00-d5d1-11eb-8f51-bcaeb666183d.png)

2021-06-28 09:36 UTC, iwiederhold requested changes
There are some IAD/VD problems with the table headers.

2021-06-29 08:13 UTC, M-Behr approved these changes
Well done! 👍

2021-06-29 08:30 UTC, iwiederhold submitted a review, later dismissed

2021-07-06 12:41 UTC, suschneider requested changes

2021-07-08 09:13 UTC, suschneider approved these changes

2021-07-08 10:17 UTC, merged