Feature/single quickorder
intershop/intershop-pwa pull request #745
Opened 2021-06-24 09:37 UTC by cbratsch

## PR Type

[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #694 

## What Is the New Behavior?

Direct order is available on cart page, when quickorder feature is toggled.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-06-28 14:41 UTC, iwiederhold reviewed
Hi, there are some old VD and IAD issues pending.
It would be nice, if these bugs can be fixed in addition.
THX.

2021-06-28 15:47 UTC, M-Behr requested changes
It works very well. I found some (smaller) issues:

- [x] Rename error message: "Please enter a valid product number!" => "The product ID 1234 does not exist." => It should be equal with error messages in quick order form. Maybe you can use the same key and we adapt the message for both places.
- [x] "Continue Shopping" link is not part of this section and should be displayed in an extra row. It is something like "Back to Homepage" and it is the last link in this content area. See detail pages in My Account as reference, e.g. Order detail page.
- [x] The "check" icon for the input field overlaps the arrows. Perhaps you can move it a little to the left. Alternatively, we can display the custom input without "Check" icon.
- [x] Please remove the 15px padding between the input fields so that they are closer together.
- [ ] Please move the "Add to Cart" button to the right until end of table. Then we can make the quantity field larger.
- [x] The "Add to Cart" button enlarges when I enter an invalid product ID. Possibly it has something to do with the disabled state.
- [x] The "Add to Cart" button needs some time to switch to disabled state. You can click "Add to Cart" in the meantime. An error message is displayed and the inputs are removed. I would prefer that the entered inputs are displayed in case of an error message. See promotion code behavior as example => Enter an invalid code and click "Apply". The code is still visible in the input field.
- [ ] After successful adding to the cart, please show button in initial state (disabled) to avoid error messages.
- [ ] Some spacing is missing in the responsive layout.

Screenshot - Desktop:
![2021-06-28 17_12_08-Your Shopping Cart _ Intershop PWA](https://user-images.githubusercontent.com/66066967/123665477-9d137b80-d838-11eb-82ad-0e392598f698.png)

Screenshot - Responsive:
![2021-06-28 17_07_27-Your Shopping Cart _ Intershop PWA](https://user-images.githubusercontent.com/66066967/123665537-a997d400-d838-11eb-9c8c-0a84e8588fe7.png)

2021-06-30 04:48 UTC, cbratsch commented
> * [ ]  The "check" icon for the input field overlaps the arrows. Perhaps you can move it a little to the left.


This seems to be the first regular number input field we have. So I have different proposals for the check icon.
- move it simply a bit to the left could looks nasty with large numbers 
![image](https://user-images.githubusercontent.com/57700960/123903301-b9b1cf80-d96e-11eb-8ca9-16dfe3c2c4ce.png)
![image](https://user-images.githubusercontent.com/57700960/123903326-c7ffeb80-d96e-11eb-8f3d-6e3ae01bb2bf.png)

- maybe it's better this way
![image](https://user-images.githubusercontent.com/57700960/123903367-de0dac00-d96e-11eb-984e-380c5647ca33.png)
![image](https://user-images.githubusercontent.com/57700960/123903377-e1a13300-d96e-11eb-802b-b44447a7e8ef.png)

2021-06-30 06:32 UTC, iwiederhold commented
Why not limit the number?

2021-06-30 07:18 UTC, M-Behr commented
> > * [ ]   The "check" icon for the input field overlaps the arrows. Perhaps you can move it a little to the left.
> 
> This seems to be the first regular number input field we have. So I have different proposals for the check icon.
> 
> * move it simply a bit to the left could looks nasty with large numbers
>   ![image](https://user-images.githubusercontent.com/57700960/123903301-b9b1cf80-d96e-11eb-8ca9-16dfe3c2c4ce.png)
>   ![image](https://user-images.githubusercontent.com/57700960/123903326-c7ffeb80-d96e-11eb-8f3d-6e3ae01bb2bf.png)
> * maybe this way
>   ![image](https://user-images.githubusercontent.com/57700960/123903367-de0dac00-d96e-11eb-984e-380c5647ca33.png)
>   ![image](https://user-images.githubusercontent.com/57700960/123903377-e1a13300-d96e-11eb-802b-b44447a7e8ef.png)
> * or we use build a custom number input like for the quantity of cart products. But this seems to have no check. So there is the same problem like before.
>   ![image](https://user-images.githubusercontent.com/57700960/123904408-b61f4800-d970-11eb-9f1c-335fc0ae000a.png)

I like the custom number input. We use it in order templates and quote requests too. There we display no "check" icon, which is fine for me. If a customer allows very large numbers, they have to adjust the field anyway.

2021-06-30 07:46 UTC, M-Behr commented
> Why not limit the number?

It's a cart configuration in the ICM. The customer can limit the amount of products in the cart. Our default is 100 but it should be possible to display larger numbers. With the custom input field we can display 7-digit numbers, which should be fine for now.

2021-07-01 13:01 UTC, M-Behr requested changes
Nice work. It looks and behave better than before. I found some minor things:

- [x] The initial state of the quick order component is not displayed after adding product with "Add an item to Cart" section. The disabled cart button and the default qty of 1 are not set. It needs a reload of the page to fix it. 
![2021-07-01 14_49_12-Your Shopping Cart _ Intershop PWA](https://user-images.githubusercontent.com/66066967/124127939-92e1bf00-da7c-11eb-9584-f1f413c8d666.png)
- [x] The custom input field displays no error message and a "cross" icon in error case. Please make the behavior consistent to the other custom input fields.
![quickorder_cart_error](https://user-images.githubusercontent.com/66066967/124128292-ee13b180-da7c-11eb-85c1-266020b14da4.png)

2021-07-02 07:20 UTC, SGrueber commented
for the quantity input the <ish-product-quantity> component should be used, only this way it is the same behavior and look and feel all over the whole application. A combined input (variation and quantity) you can find on the product detail page

2021-07-05 11:13 UTC, cbratsch commented
> for the quantity input the ish-product-quantity component should be used, only this way it is the same behavior and look and feel all over the whole application. A combined input (variation and quantity) you can find on the product detail page

I changed the component and use now the product-quantity component in the form.
There is still an issue. The quantity field shows an error for the initial state and an invalid sku. Actually I have no good idea how to fix this issue. Maybe you can take a look on this or @dhhyi can give me a hint on this.

2021-07-06 15:55 UTC, SGrueber requested changes

2021-07-06 15:55 UTC, SGrueber commented on src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
> +  model = { sku: '', quantity: 1 };
quantity must not be part of the model

2021-07-06 15:55 UTC, SGrueber commented on src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
> +    this.context
this is redundant

2021-07-06 15:55 UTC, SGrueber commented on src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
> +    this.shoppingFacade.addProductToBasket(this.model.sku, this.model.quantity);
use addProductToBasket of the productContext facade

2021-07-06 15:55 UTC, SGrueber commented on src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
> +    this.context.set('sku', () => ' ');
this is not working at all because empty sku s are currently filtered in the product context facade

2021-07-06 15:55 UTC, SGrueber commented on src/app/extensions/quickorder/shared/direct-order/direct-order.component.ts
> +        'templateOptions.required': () => (!this.directOrderForm.untouched ? !!this.model.quantity : false),
read the quantity and the quantityError from the context facade, see product-add-to-basket component this.hasQuantityError$ = this.context.select('hasQuantityError');

2021-07-16 12:12 UTC, M-Behr approved these changes
It works and looks great - even better than in responsive starter store 👍 
Please still fix the little typo in the error message. Thanks a lot!

2021-07-16 13:22 UTC, M-Behr submitted a review, later dismissed

2021-07-20 08:07 UTC, SGrueber approved these changes

2021-07-20 09:05 UTC, merged