refactor: adapt checkout shipping page with formly
intershop/intershop-pwa pull request #772
Opened 2021-07-07 08:44 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-07-09 10:44 UTC, SGrueber commented
Automatic preselection of a shipping method is not working any more:
- login and add products to basket, checkout
- on checkout address page add an Bulgarian address
- continue checkout
- > on checkout shipping page the international express delivery is displayed but not selected

2021-07-09 10:51 UTC, SGrueber commented
![image](https://user-images.githubusercontent.com/57660644/125067241-46b60080-e0b4-11eb-9940-6260adb92c45.png)
 
Please remove the 'b' :-)

2021-07-09 13:34 UTC, SGrueber requested changes
Under certain circumstances 2 patch requests are send to the sever after the shipping method has been changed:
- first patch request is fine
- second path request sets the shipping method to the first value

imo, the many observables of the checkout-shipping.component are too dynamic and they influence each other, so the code is really hard to understand.
I assume after changing the shipping method the basket is recalculated and retrieved from the server, that triggers the setupShippingMethodPreselection() functionality.

2021-07-13 06:32 UTC, MaxKless commented on src/app/pages/checkout-shipping/checkout-shipping-page.component.html
> +          b
haha woops

2021-07-13 06:32 UTC, MaxKless commented on src/app/pages/checkout-shipping/checkout-shipping-page.component.ts
> +   * leads to next checkout page (checkout payment)
not sure where that came from, I don't remember changing it. Fixed.

2021-07-19 09:05 UTC, merged