Bugfix/ssl certificate error message
intershop/intershop-pwa pull request #779
Opened 2021-07-09 11:53 UTC by Eisie96

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

When ICM backend is not protected with a valid SSL certificate the SSR rendering process logs a not very helpful message into std-out.

Issue Number: Closes #756

## What Is the New Behavior?

Log some information into SSR std-out that SSL trust cannot be established.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-09 16:06 UTC, jometzner requested changes

2021-07-09 16:06 UTC, jometzner commented on server.ts
> -  const ICM_BASE_URL = process.env.ICM_BASE_URL || environment.icmBaseURL;
Moving this to a larger scope means that it lacks a "falsey" check at the right time. You are accessing this value in function `run()` but the falsey check is performed in `app` function. To late...

2021-07-10 09:10 UTC, dhhyi commented on server.ts
> +      if (certErrorCodes.indexOf(e.code) > -1) {
[Array.includes](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

2021-07-10 09:15 UTC, dhhyi commented on server.ts
> +  const https = require('https');
Shouldn't this check only be done if the ICM_BASE_URL actually starts with https? This check will always fail if I use a local URL without TLS

2021-07-12 09:30 UTC, jometzner approved these changes

2021-07-12 12:17 UTC, jometzner submitted a review, later dismissed

2021-07-12 12:40 UTC, jometzner approved these changes

2021-07-12 12:56 UTC, merged