feat: refactor wishlist modal with formly
intershop/intershop-pwa pull request #785
Opened 2021-07-14 08:27 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-07-20 11:00 UTC, iwiederhold submitted a review, later dismissed

2021-07-20 11:05 UTC, M-Behr approved these changes

2021-07-21 11:49 UTC, SGrueber requested changes

2021-07-21 11:49 UTC, SGrueber commented on src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
> +  changeDetection: ChangeDetectionStrategy.Default,
Is this change necessary?

2021-07-21 11:49 UTC, SGrueber commented on src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
> +    this.singleFieldConfig = [
maybe a comment about the blocks would be helpful. What is meant with singleFieldConfig,  wishlistOptions and multifieldconfig?

2021-07-21 11:49 UTC, SGrueber commented on src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
> +    this.wishlistOptions$ = this.wishlistsFacade.wishlists$.pipe(
can you move this wishlistOptions functionality to the  wishlist.facade? with a boolean parameter like 'forMoving' or something like that

2021-07-21 11:49 UTC, SGrueber commented on src/app/extensions/wishlists/shared/select-wishlist-modal/select-wishlist-modal.component.ts
> +  }
This component has still a lot of lines of code. Consider to outsource the multiplefield form functionality in an extra component

2021-07-21 11:49 UTC, SGrueber commented on src/app/shared/formly/dev/testing/formly-testing.module.ts
> +  template: `RadioFielComponent: {{ field.key }} {{ field.type }} {{ to | json }} `,
typo?

2021-07-21 12:26 UTC, MaxKless commented on package-lock.json
> +    "bindings": {
no, just happened when I npm installed

2021-07-23 11:25 UTC, SGrueber requested changes

2021-07-23 11:25 UTC, SGrueber commented on src/app/extensions/wishlists/facades/wishlists.facade.ts
> +  wishlistSelectOptions$(filterCurrent = true) {
nice :-)

2021-07-23 11:25 UTC, SGrueber commented on src/app/extensions/wishlists/shared/select-wishlist-form/select-wishlist-form.component.spec.ts
> +  it('should be created', () => {
some more tests would be useful, maybe some tests can be moved from the select-wishlist-modal

2021-07-26 08:12 UTC, merged