use formly to create the login form
intershop/intershop-pwa pull request #791
Opened 2021-07-20 09:09 UTC by SGrueber

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
The login form is implemented based on the Angular reactive forms module.

## What Is the New Behavior?
The login form is created with the help of the formly module.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-21 12:39 UTC, M-Behr submitted a review, later dismissed
Perfect 👍

2021-07-22 09:58 UTC, MaxKless requested changes

2021-07-22 09:58 UTC, MaxKless commented on src/app/shared/components/login/login-form/login-form.component.spec.ts
> +        FormlyModule.forRoot({
Don't use the FormlyTestingComponentsModule, just use the FormlyTestingModule. It includes a preconfigured FormlyModule and the ReactiveFormsModule. FormlyTestingComponentsModule is for testing types, wrappers etc

2021-07-22 09:58 UTC, MaxKless commented on src/app/shared/formly/formly.module.ts
> +    FormlyBaseModule.forChild({
This is not a problem. I double checked the formly source code and there should not be any problems with this :)

2021-07-22 09:58 UTC, MaxKless commented on src/app/shared/formly/types/text-input-field/text-input-field.component.ts
> +      throw new Error(
Very nice :)

2021-07-22 10:04 UTC, iwiederhold approved these changes
YESSSSSSS!

2021-07-22 13:20 UTC, MaxKless approved these changes

2021-07-22 13:29 UTC, merged