refactor: adapt order template modal with formly
intershop/intershop-pwa pull request #792
Opened 2021-07-20 10:31 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently, the order template modal still uses the old way of defining forms. We want to change this to formly as part of the rework.

## What Is the New Behavior?

Now, the order template modal uses formly to construct the form. Additionally, the component has been refactored to be more functional.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-20 11:05 UTC, iwiederhold approved these changes

2021-07-20 11:43 UTC, M-Behr requested changes
I found a small issue:
Click "Add to Order Template" on a product tile and afterwards "Cancel" in the modal. Click the "Add to Order Template" button again to open the modal. The default selection and the prefilled input field is missing:
![2021-07-20 13_17_58-inTRONICS Home _ Intershop PWA](https://user-images.githubusercontent.com/66066967/126315994-883c8e83-10dd-4817-a77c-c883641f8466.png)
Notes:
- If you click "Add to Order Template" on another product or refresh the page, then it works fine. You has to click the same "Add to Order Template" button that you pressed first.
- If I close the modal by clicking on the background, then the last display of the modal is displayed again when I reopen it.
- Everything works great with the wish list (the other PR).

2021-07-21 06:56 UTC, M-Behr approved these changes
It looks good. Nice!

2021-07-26 15:05 UTC, SGrueber approved these changes

2021-07-26 15:06 UTC, merged