Refactor/unify and add translation keys for general error messages
intershop/intershop-pwa pull request #797
Opened 2021-07-26 08:18 UTC by cbratsch

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[x] Other: 

## What Is the Current Behavior?
standard error messages for formly fields

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-26 09:30 UTC, M-Behr requested changes
Please update error messages:
"form.email.error.required": "Please enter your e-mail address."
 "form.password.error.required": "Please enter a password."

2021-07-27 07:52 UTC, M-Behr requested changes
The English text is fine, but I changed the required e-mail error message from "Please enter an e-mail address." in "Please enter your e-mail address." because of a personal feeling and to match the pattern with first name, last name, phone, etc.

However, the localization files also need an update:
"form.email.error.required": "Bitte geben Sie Ihre E-Mail-Adresse an.",
"form.email.error.required": "Veuillez entrer votre adresse courriel."
Is this fine for you, @marschmidt89?

2021-07-27 09:10 UTC, MaxKless requested changes

2021-07-27 09:10 UTC, MaxKless commented on src/app/shared/formly/types/password-field/password-field.component.ts
> +      password: 'form.password.password.invalid',
this should be form.password.error.invalid
![image](https://user-images.githubusercontent.com/34165455/127128289-75d0e28e-9fd6-4734-91be-5386fe882eb6.png)

2021-07-27 09:40 UTC, MaxKless approved these changes

2021-07-27 10:23 UTC, M-Behr approved these changes

2021-07-27 12:56 UTC, merged