refactor: adapt account-address component with formly
intershop/intershop-pwa pull request #800
Opened 2021-07-26 13:55 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently, the account-address component uses the old select-address component, which is a specification of ish-select.

## What Is the New Behavior?

Now, the page uses formly and is refactored to be more functional.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-26 15:25 UTC, SGrueber commented
Pls ensure both select boxes have always the same (max) width

![image](https://user-images.githubusercontent.com/57660644/127015483-57327c18-8137-4d32-875a-4549187dd4fc.png)

2021-07-26 16:01 UTC, SGrueber requested changes

2021-07-26 16:01 UTC, SGrueber commented on src/app/pages/account-addresses/account-addresses/account-addresses.component.ts
> +          // distinctUntilChanged(([paddresses, puser], [caddresses, cuser]) => paddresses === caddresses),
???

2021-07-27 08:25 UTC, M-Behr reviewed
I had some issues during the review. I can't create a new address. I got the success message but the address form was still open and no new address was displayed. Also when I wanted to change the preferred address, it was not displayed. After relogging, it works perfectly. I could not reproduce this behavior.
I made a screenshot of an error in the console. Maybe this is helpful for you. Please have a look at it and check if all works well. Thank you.

![errormessage_address_myaccount](https://user-images.githubusercontent.com/66066967/127121828-b9a7a3f7-ef05-4bda-bc08-3f0df741e49a.png)

2021-07-27 10:02 UTC, M-Behr approved these changes

2021-07-28 08:40 UTC, iwiederhold approved these changes

2021-07-28 14:19 UTC, SGrueber approved these changes

2021-07-28 14:27 UTC, merged