docs: add code documentation for formly things
intershop/intershop-pwa pull request #806
Opened 2021-07-28 14:30 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[x] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently, Formly is mostly documented in formly.md

## What Is the New Behavior?

Now, every formly component, type, wrapper and extension has a summary and list of relevant templateOptions as well as a guide for using it.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-07-30 10:09 UTC, SGrueber requested changes

2021-07-30 10:09 UTC, SGrueber commented on src/app/shared/formly/types/password-field/password-field.component.ts
> + * field of type 'password', consider using ``text-input-field``.
good!

2021-08-02 07:21 UTC, MaxKless commented on src/app/shared/formly/components/validation-icons/validation-icons.component.ts
> + * @templateOption **showValidity** - a function of type ``(field: FormlyFieldConfig) => boolean``
Yes, it's consumed in the html file and defined for example in the server-validation.extension.ts

2021-08-02 12:45 UTC, SGrueber approved these changes

2021-08-02 13:26 UTC, merged