create cost center store
intershop/intershop-pwa pull request #807
Opened 2021-07-29 04:52 UTC by cbratsch

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Issue Number: Closes #

## What Is the New Behavior?

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-08-06 13:03 UTC, SGrueber requested changes

2021-08-06 13:03 UTC, SGrueber commented on src/app/shared/components/checkout/cost-center-selection/cost-center-selection.component.html
> +<ng-container *ngIf="showSelection">
(costCenterOptions$ | async)?.length && isBusinessCustumer | async

something like this

2021-08-23 11:36 UTC, M-Behr requested changes
Hi, it works really well. Here are some issues:

- [ ] Cost Center ID and name should be displayed in the buyer box at the end of checkout.
- [x] You select a cost center and go to checkout. If you click "Return to Cart" or you come back to the cart page somehow else, the cost center selection is empty. The selected cost center should be displayed. - this needs the appropriate fix of the ICM cost center REST interface (latest LTS patch)

2021-08-30 11:57 UTC, iwiederhold approved these changes
Looks fine!

2021-08-30 14:40 UTC, M-Behr reviewed
Great job! 👍

2021-08-30 14:42 UTC, M-Behr approved these changes

2021-09-01 13:31 UTC, merged