refactor: improve formly/form css styling
intershop/intershop-pwa pull request #816
Opened 2021-08-03 13:25 UTC by SGrueber

## PR Type

[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
There are some duplicate css stylings for formly and regular form artifacts.

Issue Number: Closes #

## What Is the New Behavior?
There are no duplicate form stylings any more.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2021-08-03 14:17 UTC, MaxKless requested changes
Found a couple of things: 
- The checkmark styling is not green anymore :(
![image](https://user-images.githubusercontent.com/34165455/128031244-ba4cc549-b267-4a97-a48b-64cf94080992.png)
- Currently, descriptions on invalid fields are not red. With your PR, they are also styled red. What's the correct behavior here?
![image](https://user-images.githubusercontent.com/34165455/128031580-33468870-2e61-4509-89c0-c6aac3c17e33.png)
![image](https://user-images.githubusercontent.com/34165455/128031645-7932fe22-5899-4cb2-867c-1f0ec5330a8f.png)

2021-08-03 15:13 UTC, shauke requested changes

2021-08-03 15:13 UTC, shauke commented on src/styles/main.scss
> -@import 'global/forms/formly';
If you remove the import of `formly.scss` shouldn't the file `formly.scss` be removed as well? Currently it contains unimported styles.

2021-08-03 15:13 UTC, shauke commented on src/styles/global/forms/forms.scss
> +.formly-empty-label {
This seems to be the only CSS class with `formly` in its name. Maybe this is something that could be named more general? Especially in `forms.scss`. ;)

2021-08-04 12:45 UTC, MaxKless approved these changes
Don't see anything wrong with the code and all my issues work now :)

2021-08-04 13:16 UTC, shauke approved these changes

2021-08-04 13:50 UTC, merged