chore: update tslint to eslint
intershop/intershop-pwa pull request #836
Opened 2021-08-16 10:09 UTC by MaxKless

## PR Type

[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[x] Build-related changes
[x] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

Currently, we use the deprecated tslint.

## What Is the New Behavior?

Now, eslint is used.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

2021-11-03 12:49 UTC, cbratsch commented
Rule fixer for sorting imports doesn't work, when first line is empty.
Please check.

2021-12-13 13:25 UTC, Eisie96 requested changes

2021-12-13 13:25 UTC, Eisie96 commented on eslint-rules/src/rules/use-jest-extended-matchers-in-tests.ts
> +const REPLACEMENTS = [
Why is this configuration directly included in the lint rule instead as a configuration in the eslintrc.json?

2021-12-13 13:25 UTC, Eisie96 commented on eslint-rules/src/rules/use-jest-extended-matchers-in-tests.ts
> +      'Identifier[name=/(toBe|toEqual)/]'(node: TSESTree.Identifier) {
Should this rule always check toBe or toEqual calls? Could this be also a configuration?

2021-12-14 08:41 UTC, MaxKless commented on eslint-rules/src/rules/no-assignment-to-inputs.ts
> +    if (context.getFilename().search(/.(component|container).ts/) < 0) {
`isComponent` checks a `ClassDeclaration` node but this is before we have access to any nodes based purely on the file name.

2021-12-14 09:03 UTC, MaxKless commented on eslint-rules/src/rules/use-alias-imports.ts
> +        pattern: `.*/${paths[key][0].replace(/\/\*$/, '/')}`,
as talked about, skipping this one because it doesn't rly makes sense

2021-12-14 09:27 UTC, Eisie96 requested changes

2021-12-15 14:40 UTC, Eisie96 requested changes

2022-01-05 09:16 UTC, shauke commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
The dependencies update will be done with the Angular 13 update. We will start with this set for now.

2022-01-10 13:55 UTC, marschmidt89 submitted a review, later dismissed
documentation review done

2022-01-17 08:36 UTC, shauke approved these changes
Very nice migration. I would say this should be all right now and ready to be merged.

2022-01-17 09:03 UTC, merged