feature: product attachments
intershop/intershop-pwa pull request #840
Opened 2021-08-18 13:14 UTC by suschneider

## PR Type
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?

The PWA does currently not support the display of product attachments.

Issue Number: Closes #767

## What Is the New Behavior?
Product attachment information are displayed on product detail page similar to the Responsive Starter Store regarding the IAD changes mentioned in issue #767.

## Does this PR Introduce a Breaking Change?
[ ] Yes
[x] No

2021-08-20 12:16 UTC, SGrueber requested changes

2021-08-23 08:22 UTC, SGrueber approved these changes

2021-08-30 14:35 UTC, M-Behr approved these changes
Perfect! 👍

2021-08-30 15:28 UTC, shauke approved these changes
👍

2021-08-31 07:19 UTC, merged