feat: punchout identity provider
intershop/intershop-pwa pull request #916
Opened 2021-10-28 07:11 UTC by Eisie96

## PR Type

[x] Feature

## What Is the Current Behavior?

OCI Punchout Sessions gets lost after Reload.

Issue Number: Closes #

## What Is the New Behavior?

OCI Punchout Sessions is available after Reload. Therefore is the punchout guard refactored to a new identity provider, which saves the actual basketId to the session storage. Furthermore it is possible to override the actual identity provider on specific routes. 

## Does this PR Introduce a Breaking Change?

[ ] Yes
[ ] No

## Other Information

[AB#70891](https://dev.azure.com/intershop-com/cefd1005-00a7-4c79-927f-a16947d1b2e6/_workitems/edit/70891)

2021-11-08 15:23 UTC, MaxKless requested changes

2021-11-08 15:23 UTC, MaxKless commented on src/app/extensions/punchout/identity-provider/punchout-identity-provider.ts
> +              // TODO: if load basket error (currently no error page) -> logout and do not use default 'current' basket
Are you planning on handling these TODOs? Or is that for a later time?

2021-11-08 15:41 UTC, Eisie96 commented on nginx/entrypoint.sh
> +  if [ -n "$OVERRIDE_IDENTITY_PROVIDERS" ]
-n stands for not null. The entryproypoint checks only the case, if the environment variable OVERRIDE_IDENTITY_PROVIDERS was set. If so, OVERRIDE_IDENTITY_PROVIDERS_SOURCE gets the yaml parsed value from that variable.

2021-11-15 11:58 UTC, MaxKless submitted a review, later dismissed
Great job!

2021-11-15 15:59 UTC, MaxKless commented
Sadly, I found a bug when opening two windows with OCI punchout when using a static punchout identity provider.
Steps to repeat:
- start an OCI punchout session 
- open a second window of the PWA and open another OCI punchout session
- add different items to the cart so you can easily distinguish between the two sessions
- reload one window (sometimes twice or more)
- open the other window and see the confusing behavior


When building the PWA with `ng serve`, the other window will be logged out.
When building the PWA with `docker-compose`, the other window will be logged out and a tiny sign-in window appears:
![image](https://user-images.githubusercontent.com/34165455/141812544-6ad68f0a-e66f-4ce6-9669-028e55b56546.png)

2021-11-22 12:28 UTC, merged