fix: unify budget input fields layout in phone view (#957)
intershop/intershop-pwa pull request #966
Opened 2021-12-21 11:46 UTC by SGrueber

## PR Type

[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no API changes)
[ ] Build-related changes
[ ] CI-related changes
[ ] Documentation content changes
[ ] Application / infrastructure changes
[ ] Other: 

## What Is the Current Behavior?
There are some minor ui issues in the cost center management.

Issue Number: Closes #957

## What Is the New Behavior?
The minor cost center ui issues have been fixed.

## Does this PR Introduce a Breaking Change?

[ ] Yes
[x] No

## Other Information

2022-01-04 13:13 UTC, Eisie96 approved these changes

2022-01-04 13:25 UTC, Eisie96 approved these changes

2022-01-04 16:11 UTC, M-Behr requested changes
It looks very well 👍 

Already spent displays "undefined0.00" for approved requisitons (in case of unlimited budget). It works fine for pending requisitions. Could you check this, please?

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/66066967/148088871-933a1f0e-7858-4375-9188-a0e719ad50ff.png)

2022-01-06 16:26 UTC, M-Behr requested changes
Now "0" is displayed instead of "$0.00". 🙈 

<img width="158" alt="image" src="https://user-images.githubusercontent.com/66066967/148415049-4a30e40f-33a1-4281-b885-7ae1c2a4adc2.png">

2022-01-07 14:32 UTC, merged