feat: replace product detail info accordion with tabs
intershop/intershop-pwa pull request #994
Opened 2022-02-01 12:11 UTC by suschneider

## PR Type
[x] Feature

## What Is the Current Behavior?
Detailed information about a product, such as a long description or product attributes, is displayed on product detail page with an accordion.

## What Is the New Behavior?
This information is displayed with tabs.

## Does this PR Introduce a Breaking Change?
[ ] Yes
[x ] No

2022-02-01 15:29 UTC, SGrueber requested changes
pending: 
- remove unused styles in productdetail.scss (done)
- clarify if the accordion and accordion-item component should be removed? (will keep)
- fix e2e tests (done)

2022-02-01 15:29 UTC, SGrueber commented on src/app/pages/product/product-detail-info/product-detail-info.component.html
> +    <li *ngIf="product.attributes && product.attributes.length" [ngbNavItem]="'DETAILS'">
use product.attributes?.length

2022-02-01 15:29 UTC, SGrueber commented on src/app/pages/product/product-page.module.ts
> +  exports: [ProductDetailInfoComponent],
exports is not necessary because you use it only on (within) product detail page

2022-02-01 15:29 UTC, SGrueber commented on src/app/pages/product/product-detail-info/product-detail-info.component.spec.ts
>  describe('Product Detail Info Accordion Component', () => {
Product Detail Info Component

2022-02-03 14:20 UTC, SGrueber submitted a review, later dismissed

2022-02-04 09:12 UTC, SGrueber approved these changes

2022-02-05 21:53 UTC, shauke approved these changes

2022-02-05 21:54 UTC, merged